### ISSUE TITLE
Issue: Getting "No prompt owner specified" when attempting to pull a private prompt

### ISSUE THREAD

**Issue by Lukecn1** [langchain-ai/langsmith-sdk#1007]
### Issue you'd like to raise.

I cannot pull a private prompt from my workspace without getting a "no prompt owner specified error". The issue persists when giving the workspace name, the organization name or any other id relevant to my account. 

Code that produce the error:

`import os
from langsmith import Client
from dotenv import load_dotenv
load_dotenv()

client = Client(api_key=os.getenv("LANGSMITH_API_KEY"))

prompt = client.pull_prompt(prompt-id)`
 
I have verified my API key and the loading of it several times. 

The issue persists even when I use export LANGCHAIN_APY_KEY in terminal before running the code.

**Comment by mfaux** [comment]
Hi @Lukecn1 , I'm also getting this error. How did you resolve it?

**Comment by mfaux** [comment]
I found that I was pointing to the wrong endpoint. 

Instead of:
```
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
```

I needed the European server:
```
LANGCHAIN_ENDPOINT="https://eu.api.smith.langchain.com"
```

**Comment by KodyKendall** [comment]
I am running into this same issue now.
