### ISSUE TITLE
about renaming to langsmith

### ISSUE THREAD

**Issue by natsukium** [langchain-ai/langsmith-sdk#104]
Hello, thank you for your daily development.
I really appreciate it.

I'm working on packaging langchain in [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs).
I found this [issue](https://github.com/hwchase17/langchain/issues/5905#issuecomment-1633323516). Is it right to understand that langchainplus-sdk has been wholly replaced by langsmith?
If so, I'm planning to remove the langchainplus-sdk package from `nixpkgs`.

I also noticed in the above issue that this code is now open.
Thanks for making it public!

**Comment by hinthornw** [comment]
Thanks for your patience, @natsukium ! That's correct! I'll update those packages to mark as deprecated. The SDK will henceforth be the `langsmith` package. Thank you!

**Comment by r7l** [comment]
Why not rename the repo then? It's kinda confusing to have a repo called **langchainplus-sdk** when the project is actually called **langsmith**.

**Comment by hinthornw** [comment]
@r7l Seems I renamed it right after you commented - reason was just time
