### ISSUE TITLE
Limit on List Prompt Commits not being respected it seems

### ISSUE THREAD

**Issue by luisramirez7** [langchain-ai/langsmith-sdk#1042]
### Issue you'd like to raise.

The `limit` field in the `list_prompt_commits` seems to not be respected. I've written a unit test to grab the commits using the Client method, and debugged into it. Here is what I'm seeing: 

First, the assertion error when limit is set to 1, asserting that there is only 1 commit returned.

```
# Test case 2: List commits with limit
limited_commits = list(manager.list_prompt_commits(name, limit=1))
```
<img width="1325" alt="Screenshot 2024-09-25 at 12 17 03 PM" src="https://github.com/user-attachments/assets/4c5b51a4-a7c6-43dd-817b-d39677922517">

Stepping into the code, we see it yielding for all the commits that the prompt has; that's all well and good, as we see that the limit is correctly set to 1, and the `items` property correctly only has 1 commit. 

<img width="1225" alt="Screenshot 2024-09-25 at 2 08 09 PM" src="https://github.com/user-attachments/assets/d98aedf4-c263-4c70-8ebc-033c993ca231">

Yet, when we return from the method back into the test:
<img width="1243" alt="Screenshot 2024-09-25 at 2 10 23 PM" src="https://github.com/user-attachments/assets/c0927959-1812-4f48-b659-6dc54576570b">
We see that the length of limited_commits = 4, instead of 1. 

### Suggestion:

Debug limit flag on list_prompt_commits. Maybe this has something to do with the while true and yield loop.

**Comment by luisramirez7** [comment]
hm, upon further reading this may be expected behavior. Unclear. If so, feel free to close.
```
Note:
            This method uses pagination to retrieve commits. It will make multiple API calls if necessary to retrieve all commits
            or up to the specified limit.
so I'm assuming the limit is used only for pagination
```

**Comment by hinthornw** [comment]
Thanks for flagging

**Comment by hinthornw** [comment]
Should be fixed now! LMK if you still run into issues
