### ISSUE TITLE
Retrieve threads via API

### ISSUE THREAD

**Issue by alexnodeland** [langchain-ai/langsmith-sdk#1045]
### Feature request

Currently, the LangSmith API provides methods to retrieve runs and their metadata, but does not include the `thread_id` parameter. I would be useful to include the `thread_id` in the run metadata. Furthermore, it would be useful to have a thread route on the LangSmith API, in order to retrieve collections of runs, grouped by thread_id.

### Motivation

I want to build a system that allows users to clone threads and share them with other users, to continue working with on their own account.

**Comment by hinthornw** [comment]
Thanks for writing in! And good question.

A thread's `thread_id` IS metadata.

You can fetch from the SDK/API by specifying the thread_id you want in metadata. See the doc on exporting traces for some more info: [link](https://docs.smith.langchain.com/how_to_guides/tracing/export_traces#list-all-root-runs-in-a-conversational-thread)

This is how the UI itself works :)
