### ISSUE TITLE
version tag conflict

### ISSUE THREAD

**Issue by natsukium** [langchain-ai/langsmith-sdk#105]
This repo uses the langchainplus-sdk as it is now.
As you can see from the tags and releases, there is a conflict between langchainplus-sdk's tags and langsmith's.
Since you released v0.0.7, it has been released daily with the tag "v".
Although the PyPI packages seem to be successfully released from the CI, I cannot trust that it is the correct version without comparing the source code.

I believe that proper tagging is helpful for both users and maintainers.

Thanks again for developing this. ❤️

**Comment by hinthornw** [comment]
Thank you! I'll work to fix our CI. It indeed is broken

**Comment by hinthornw** [comment]
I believe this should be fixed for python but I'll leave this open for another couple versions just to confirm.

Still broken for adding JS. Will probably migrate out to be separate repos

**Comment by hinthornw** [comment]
Think this should be resolved now
