### ISSUE TITLE
Issue: "project_name" @traceable or LANGCHAIN_PROJECT being ignored

### ISSUE THREAD

**Issue by majorgilles** [langchain-ai/langsmith-sdk#1068]
### Issue you'd like to raise.

Why trying to run an AI function with the following decorator:
```
@traceable(
    client=langsmith_client,
    project_name="Picture Categorization",
)
def my_ai_function(...)...
```
The langsmith expriment works perfectly by sending the data to langsmith UI, but unfortunately the project is incomprehensible: it sends all results to the "evaluators" project which I have never set in code.

Trying to set an env variable via ```LANGCHAIN_PROJECT``` does not work either, the results are still sent to the "evaluators" project. 

No idea what is going wrong here...

### Suggestion:

The documented methods to set a dynamic project name should work out of the box without complications.
Raising an exception would be more helpful than autogenerating a project name that has (to the best of my knowledge) never been specified in code.

**Comment by hinthornw** [comment]
Hi @majorgilles - evaluations are traced within experiments. Evaluator runs are assigned metadata based on the experiment, linked to the target run, but all located in the evaluators project to avoid cluttering your default or other projects with evaluator runs.
