### ISSUE TITLE
Issue: Run does not complete if key 'generations' is in the result

### ISSUE THREAD

**Issue by jmoseley** [langchain-ai/langsmith-sdk#1084]
### Issue you'd like to raise.

After quite a bit of debugging, I discovered that a trace will not be completed if the key `generations` is in the result. If there are sub-traces, those will be tracked fine, but the parent will remain as `pending`.

Here is some simple sample code:

```
export const createContent = traceable(
  async (input:string,) => void) => {
    await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: "You are a helpful assistant.",
        },
        {
          role: "user",
          content: "Hello, how are you?",
        },
      ],
    });

    const result = {
      id: "random-id",
      title: "random-title",
      content: completion.choices[0].message.content,
      generations: 1,
    };

    return result;
  },
  {
    name: "create-content",
  },
);
```

For this code, a trace named `create-content` will be started, and the trace of the open AI chat completion will be created. But the `create-context` run will remain pending, and not be completed. If `generations: 1` is commented out, then the traced will be marked as successful.

If the openai call is commented out, then no trace will be recorded at all (unless `generations: 1` is commented out as well).

### Suggestion:

I expect that this seemingly arbitrary response key would not cause the span to fail. If it does, I would expect an error or something to indicate the issue. I basically had to comment out every bit of code in the original function to discover this problem.

**Comment by agola11** [comment]
Hi @jmoseley thanks for flagging. We are investigating the issue

**Comment by agola11** [comment]
Hi @jmoseley this is actually a backend issue -- we've merged a fix and it will deploy to prod later today. Thanks again for flagging! I will close this issue but feel free to reopen if the issue continues to persist after today.

**Comment by jmoseley** [comment]
Amazing, thanks for the speedy response!
