### ISSUE TITLE
Jinja2 templates

### ISSUE THREAD

**Issue by Lukecn1** [langchain-ai/langsmith-sdk#1125]
### Feature request

I would love a feature that makes it possible to create and pull prompts in jinja2 format.

### Motivation

I (and my team) are very happy using langsmith - especially for prompt development and evaluation. 

But we need to use jinja2 templates for validation of variables in our application. 
If we could create and pull prompts to conform to the jinja2 format, that would be a great feature. 

Cheers :)

**Comment by hinthornw** [comment]
I believe we removed support a while back because it has / had security vulnerabilities. We don't currently plan to add support for it.
