### ISSUE TITLE
Issue: Runs are not showing up for a new project

### ISSUE THREAD

**Issue by aaron-dsouza** [langchain-ai/langsmith-sdk#1137]
### Traces not showing up in Langsmith

I created a new account in Langsmith. I then created an API key as was suggested on the account page and then ran this example from a python notebook.

```
from langchain_openai import ChatOpenAI
import os
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_API_KEY"]=""
os.environ["OPENAI_API_KEY"]=""

llm = ChatOpenAI()
llm.invoke("Hello, world!")
```

I got this response without any errors

`AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 9, 'prompt_tokens': 11, 'total_tokens': 20, 'completion_tokens_details': {'audio_tokens': None, 'reasoning_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': None, 'cached_tokens': 0}}, 'model_name': 'gpt-3.5-turbo-0125', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None}, id='run-e913c0c1-de07-4a30-9470-d7ba996ab2c4-0', usage_metadata={'input_tokens': 11, 'output_tokens': 9, 'total_tokens': 20, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 0}})`

However in the default project In langsmith I don't see the traces corresponding to this execution.

I then created a new project in Langsmith and set the following environment variable
os.environ["LANGCHAIN_PROJECT"]="project-name"

I ran and still did not see any trace. I still only see the default project. The default project has several runs which were not created by me, e.g.
Sample Agent Trace
RunnableLambda
ChatpromptTemplate
etc.

What am I missing?

**Comment by hinthornw** [comment]
Did you try restarting the notebook kernel before running that cell?

**Comment by prashantmetadome** [comment]
Facing this issue

**Comment by chayansraj** [comment]
Try to restart the kernel, it works.
