### ISSUE TITLE
Issue: Langsmith traces out of order / missing traces

### ISSUE THREAD

**Issue by dylanjcastillo** [langchain-ai/langsmith-sdk#1142]
### Issue you'd like to raise.

Hi,

I'm encountering an issue where nested traces appear in the wrong order or aren't displayed as expected in the UI, regardless of the code I'm using.

I'm using Python 3.12, with environment variables loaded from a .env file (`LANGCHAIN_TRACING_V2=true`, along with the API key and project name).

Here's a minimal example to reproduce the issue:

```python
from langsmith import traceable

@traceable
def test_outer_function(x: int) -> int:
    result_1 = test_inner_function_1(x)
    result_2 = test_inner_function_2(result_1)
    return result_1 + result_2


@traceable
def test_inner_function_1(x_1: int) -> int:
    return x_1 + 1


@traceable
def test_inner_function_2(x_2: int) -> int:
    return x_2 + 1
```

The behavior I'm seeing is:

1. I get a trace for `test_outer_function`.
2. The trace for `test_inner_function_1` mirrors the trace of `test_outer_function`.
3. The trace for `test_inner_function_2` shows what should have been displayed for `test_inner_function_1`.
4. The trace that should have been shown for `test_inner_function_2` doesn't show anywhere.

Here's a video demonstrating the issue:

https://github.com/user-attachments/assets/d97ff0c9-6d29-4285-ad54-6cae44a0bb1b

Any ideas on to resolve this?

**Comment by jacoblee93** [comment]
Hey @dylanjcastillo, thanks for reporting and for the repro case - looking into it!

**Comment by jacoblee93** [comment]
Hey @dylanjcastillo, checked in and was told that there was a display bug in LangSmith that landed a few hours ago - can you check again?

**Comment by dylanjcastillo** [comment]
Thank you, @jacoblee93! It works now. For a moment, I thought I was going crazy.
