### ISSUE TITLE
Issue: Internal Server Error

### ISSUE THREAD

**Issue by sreyakumar** [langchain-ai/langsmith-sdk#1144]
Experiencing this issue.. langsmith.utils.LangSmithAPIError: Server error caused failure to GET /commits/eden19/filtergeneration/latest in LangSmith API. HTTPError('500 Server Error: Internal Server Error for url: https://api.smith.langchain.com/commits/[user]/[prompt]/latest', '{"detail":"Internal server 
error"}

Are there any workarounds I can do on my end?

**Comment by hinthornw** [comment]
What code are you running to get this error?

**Comment by sreyakumar** [comment]
I was importing my rag chain from another file but it seems to have resolved itself!
