### ISSUE TITLE
Issue:  output column in langsmith dashboard not displaying correctly after updating to langchain 0.3.1

### ISSUE THREAD

**Issue by kjkombat** [langchain-ai/langsmith-sdk#1242]
### Issue you'd like to raise.

I have a chain that uses bind_tools function to get output as a class object with enum. In langchain version 0.2.6 The output was working as below

![Screenshot 2024-11-21 145116](https://github.com/user-attachments/assets/d62f1f4c-7598-45f9-b35a-392c62fcbaa6)
![Screenshot 2024-11-21 150248](https://github.com/user-attachments/assets/8cb9bb35-aa02-409b-81c6-a307d6f11d2d)
![Screenshot 2024-11-21 150301](https://github.com/user-attachments/assets/bcfd2742-156d-4859-91db-c26c3d15dc4c)

After updating to langchain version 0.3.1 the same chain is now giving output as below

![Screenshot 2024-11-21 150333](https://github.com/user-attachments/assets/d5ca385c-290c-44ce-a6d4-ff21ab13f5d5)
![Screenshot 2024-11-21 150349](https://github.com/user-attachments/assets/8af0edc4-46a1-42d6-95d6-7baa33705933)
![Screenshot 2024-11-21 150357](https://github.com/user-attachments/assets/bcb5e343-0b62-488b-8e41-b585a082b18b)

This is not readable as a trace.

### Suggestion:

The output version of 0.2.6 is better to work with as it stringifies any object returned by function call which is easier for reading traces. Also, would appreciate clarity in what gets recorded in output column, only the LLM output or the final result of a chain (in case LLM output and a parser is not the final step).

**Comment by hinthornw** [comment]
Hi kjkombat - we made some optimizations to object serialization to reduce resource consumption during tracing (such as deeply unnesting regular python objects) - Does it work if you  add an `dict()` method to the ReturnRouteResponse object?

**Comment by kjkombat** [comment]
Thank you, it works fine with a ```dict()``` method to ReturnRouteResponse.
