### ISSUE TITLE
Issue: Tag filters are not working

### ISSUE THREAD

**Issue by gslmota** [langchain-ai/langsmith-sdk#1290]
### Issue you'd like to raise.

In my project, I created a custom tag called 'chat' and configured a filter to perform queries related to this tag. Initially, the filter worked normally, and I could use it without any issues. However, now, when I try to perform the query, it has stopped working. When I press 'Enter' to execute the filter, nothing happens, as if the command is not being recognized or processed.

![image](https://github.com/user-attachments/assets/58cecd85-e506-46d6-8c41-7ff5ef776108)

**Comment by martin-cycle** [comment]
Same here!
