### ISSUE TITLE
[Feature Request] Show Prompt vs. Completion Tokens per Run

### ISSUE THREAD

**Issue by dmyoung9** [langchain-ai/langsmith-sdk#130]
Current Behavior
---

Currently, the LangSmith UI appears to only allow showing prompt/completion tokens for an entire project.
![image](https://github.com/langchain-ai/langsmith-sdk/assets/101432365/8ddc64d2-92d5-488b-b5a0-c7f58f66a6f4)

The only view on this data that is available per run is *total* tokens, but not prompt tokens vs. completion tokens.
![image](https://github.com/langchain-ai/langsmith-sdk/assets/101432365/18644a56-33fe-45f8-8f2a-133025121805)

Desired Behavior
---

I'd like to be able to show columns for prompt/completion tokens per run, when viewing a project.

**Comment by hinthornw** [comment]
Hi @dmyoung9 - you can see the prompt vs. completion tokens in the run tree once you click on a run

![image](https://github.com/langchain-ai/langsmith-sdk/assets/13333726/acdd87e4-a1cd-4175-b6ce-58ffbc855f4a)

**Comment by dmyoung9** [comment]
I know you can see it there, but I'd like to be able to see them as columns in the overall view, rather than clicking into every run individually.

**Comment by hinthornw** [comment]
Sure will make a ticket

**Comment by shub-kris** [comment]
@hinthornw I would also like to have this feature.

**Comment by hinthornw** [comment]
@shub-kris and @dmyoung9 , the separation is now visible upon hover in the project table

![image](https://github.com/langchain-ai/langsmith-sdk/assets/13333726/6c7a4273-67e0-4b24-bb12-4a761bdbcf25)

**Comment by hinthornw** [comment]
I'll close this issue for now

**Comment by dmyoung9** [comment]
Yep, looks good enough to me 👌
