### ISSUE TITLE
Error: Failed to create run: 409 Conflict {"detail":"Run already exists"}

### ISSUE THREAD

**Issue by codenameakshay** [langchain-ai/langsmith-sdk#158]
Hey, I am trying to integrate Langsmith, in my LangChain chains, and I am getting the following error, when I invoke a chain - 

`Error in handler Ce, handleLLMStart: Error: Failed to create run: 409 Conflict {"detail":"Run already exists"}`
![image](https://github.com/langchain-ai/langsmith-sdk/assets/60510869/16e68f77-e5bf-454e-bed9-970180a3ef34)

I am using Deno to handle my functions and have initialised all env vars like this - 
![image](https://github.com/langchain-ai/langsmith-sdk/assets/60510869/6180291b-fae4-408e-99d2-e30c05553853)

Here is a sample of my code - 

```javascript
import { ChatOpenAI } from "langchain/chat_models/openai";
import { LLMChain } from "langchain/chains";
import { PromptTemplate } from "langchain/prompts";

import { Client } from "langsmith";
import { LangChainTracer } from "langchain/callbacks";
import { LANGCHAIN_API_KEY, LANGCHAIN_ENDPOINT, LANGCHAIN_PROJECT } from "../_shared/env.ts";

... more imports

const prompt = PromptTemplate.fromTemplate(spellCorrectPromptString);

... more code    

serve(async (req) => {
... more code

  const client = new Client({
		apiUrl: LANGCHAIN_ENDPOINT,
		apiKey: LANGCHAIN_API_KEY,
	});

	const tracer = new LangChainTracer({
		projectName: LANGCHAIN_PROJECT,
		client,
	});

  try {
    const { input: query, platform } = await req.json();  

    const llm = new ChatOpenAI({
      ...openAIOptions,
      callbacks: [tracer],
      tags: ["spell-correct"]
    }, openAIConfiguration);
    
    // For a non-streaming response we can just await the result of the
    // chain.run() call and return it.
    const chain = new LLMChain({ llm, prompt, verbose: isDevelopment});

    const response = await chain.call({ query }).catch((e) => console.error(e));

    return new Response(JSON.stringify(response), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    return new Response(JSON.stringify({ error: e.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
```

The chain shows up on the Langsmith dashboard, but it is shown as pending
![image](https://github.com/langchain-ai/langsmith-sdk/assets/60510869/b53b6727-c588-4a2c-ac59-cb75ae8e3cdd)

If I remove LangSmith everything is working perfectly, but once I integrate it like this, I get 502 on my functions (as Langsmith requests itself fail)

Please let me know if you need anything else from my end.

**Comment by hinthornw** [comment]
Going to close as stale for now. Let me know if you still have issues
