### ISSUE TITLE
[JS] Forever pending state due to user misconfiguration

### ISSUE THREAD

**Issue by bkamapantula** [langchain-ai/langsmith-sdk#170]
LangSmith trace enters a forever pending state due to a user misconfiguration. The error handling can be improved here.

Shared the LangSmith trace with @jacoblee93 privately.

To replicate, use the incorrect metadata configuration that makes a trace end up in a pending state:

```js
chain.call({
  question,
  metadata: { experiment: 'summary' },
})
```

while the correct configuration makes a trace complete as expected:

```js
chain.call({
  question,
}, {
  metadata: { experiment: 'summary' }
})
```

**Comment by hinthornw** [comment]
Going to close this as stale
