### ISSUE TITLE
[JS] Summary chain must be nested within CRQAC 

### ISSUE THREAD

**Issue by bkamapantula** [langchain-ai/langsmith-sdk#171]
Currently, the summary chain is traced as a separate chain call instead of within the nested CRQAC trace.

Replicated and shared this with @jacoblee93.

**Comment by hinthornw** [comment]
Thanks for raising! We'll make the fix

**Comment by hinthornw** [comment]
@bkamapantula are you still running into any issues?

**Comment by bkamapantula** [comment]
I'm good now, @hinthornw . Thanks for checking!

Will close the ticket.
