### ISSUE TITLE
[JS] run on dataset functionality for js/ts?

### ISSUE THREAD

**Issue by dstollie** [langchain-ai/langsmith-sdk#175]
The funtionality to run evaluators on a dataset using run_on_dataset in Python is exactly what we are looking for. Right now we've build our Langchain implementation in Typescript. I am wondering if you are working also on the same functionality in js/ts and if so do you have any expectations on when?

**Comment by hinthornw** [comment]
Made a hasty sketch of the basic functionality in JS here https://github.com/hwchase17/langchainjs/pull/2440

**Comment by imtaotao** [comment]
Is there any progress on this feature? Need help supporting implementation?

**Comment by hinthornw** [comment]
Hi @dstollie - JS has support for this now:

Quick walkthrough: https://js.langchain.com/docs/guides/langsmith_evaluation
Evals Quickstart: https://docs.smith.langchain.com/evaluation/quickstart
