### ISSUE TITLE
[Bug] No Completion Tokens shown in UI

### ISSUE THREAD

**Issue by shub-kris** [langchain-ai/langsmith-sdk#184]
Hi, I am using `traceable` operator for logging into langsmith. In the UI I just see the prompt token and the completion token is always zero. 

I am attaching the screenshot for your reference. I am not using langchain. 

<img width="452" alt="image" src="https://github.com/langchain-ai/langsmith-sdk/assets/18352477/20e62d17-da12-46d6-baa4-a7c220034726">

**Comment by hinthornw** [comment]
Thanks! Could you share a code snippet to reproduce? (just of the openai call)

**Comment by hinthornw** [comment]
Going to close as stale for now. Let me know if you still have issues
