### ISSUE TITLE
Not able to get run id based on tag or metadata

### ISSUE THREAD

**Issue by solarslurpi** [langchain-ai/langsmith-sdk#187]
I want a user to be able to provide feedback on an inference result within my chatbot ui.

The scenario is:
= user asks a question
- chatbot returns answer
- user provide feedback on answer (good/bad for example).

I would think the ideal way to write feedback to the langsmith trace/run is to get the run id when calling the chain.  I have tried two ways to do chains:
```
qa_chain = RetrievalQA.from_chain_type(
    llm,
    retriever=retriever,
    return_source_documents=True,
    chain_type_kwargs={"prompt": prompt},
)
```
and
```
qa_chain = (
    {"context": itemgetter("question") | retriever,
     "question":itemgetter("question")}
    | prompt 
    | llm 
)
```
neither chain appears to be able to get the run id from the result as noted in https://docs.smith.langchain.com/tracing/tracing-faq#how-do-i-get-the-run-id-from-a-call.

So this didn't work.

I was able to tag runs, but when I try to retrieve with the tag (or i also tried metadata), I get
```
langsmith.utils.LangSmithError: Failed to get https://api.langchain.plus/runs in LangSmith API. {"detail":"At least one of 'session', 'id', 'parent_run', or 'reference_example' must be specified"}
```
which seems to tell me that although the langsmith documentation said `list(client.list_runs(filter='has(metadata, \'{"variant": "abc123"}\')'))`, it didn't work for me.

What am i missing ? All I want is to write user feedback to a run in langsmith.  Thank you.

**Comment by hinthornw** [comment]
@solarslurpi thanks for raising! It's frustratingly inconsistent, isn't it? I just added a callback manager a couple versions ago that should help:

```
from lanchain import callbacks

with callbacks.collect_runs() as cb:
    chain.invoke("foo")
    run_id = cb.traced_runs[0].id
```

**Comment by solarslurpi** [comment]
Thank you.  I will attempt the callback.  The challenge remains - whatever chain method (LCEL or RetrievalQA in this e.g.), why can't I just get the run id back?  Then, the second challenge was I couldn't filter runs on metadata or tags.  You are right, it is frustrating.  Thank you.

**Comment by hinthornw** [comment]
"why can't i just get the run ID back" - you mean directly in the response? Generally, a lot of the existing components have expectations about what is contained in the response object (or just raw string), so we aren't adding it there.

For the second issue, we recently improved the indexing of our database to handle better scale, so you'll need to add a project name or project ID to the list call. For instance, if you are querying in the "default" project.

```python
runs = client.list_runs(project_name="default", filter='has(tags, "foo")'
```
should work

**Comment by solarslurpi** [comment]
@hinthornw The callback worked.  Wow. I would have never figured that out!  re: including the project name.  Oh. That is interesting.  Perhaps at least the error message should be updated?  Thank you.

**Comment by hinthornw** [comment]
@solarslurpi will file a ticket, yes! The confusion is that the backend still uses the old language of sessions instead of projects :/

**Comment by hinthornw** [comment]
@solarslurpi I'm going to close this for now. Feel free to re-open if you run into additional issues
