### ISSUE TITLE
Total token is not visible and the run count is not updating

### ISSUE THREAD

**Issue by ayushigithub12** [langchain-ai/langsmith-sdk#204]
![issue](https://github.com/langchain-ai/langsmith-sdk/assets/95244946/feefc670-de23-4cd0-a06a-4446698a1e5a)

**Comment by ayushigithub12** [comment]
![run_cont](https://github.com/langchain-ai/langsmith-sdk/assets/95244946/aa053883-cfd1-4a34-998c-48563885ffdf)

**Comment by hinthornw** [comment]
@ayushigithub12 thanks for raising! Could you confirm whether this is running locally /self-hosted or if it its on the hosted endpoint?

**Comment by ayushigithub12** [comment]
Its running on google colab on gpu.

**Comment by hinthornw** [comment]
Could you run `langsmith env` in the terminal on the notebook and share your langchain version, langsmith version, etc.?

So the client is running on collab. Are you connecting to https://api.smith.langchain.com? Or to a self-hosted service?

**Comment by ayushigithub12** [comment]
Yeah I run langsmith env and I found the langchain version was old,
because I haven't installed the updated version of langchain, I did the changes and now its showing.
Thanks for your help!

**Comment by hinthornw** [comment]
Excellent! I'll close this issue out then. Feel free to reopen if there are additional difficulties.
