### ISSUE TITLE
Issue: langsmith don't work and can't trace any data

### ISSUE THREAD

**Issue by ChaoZhou2023** [langchain-ai/langsmith-sdk#216]
### Issue you'd like to raise.

I tried langsmith in google colab
`
from langchain.chat_models import ChatOpenAI
import os
os.environ['OPENAI_API_KEY'] = 'My_OPENAI_API_KEY'
os.environ['LANGCHAIN_TRACING_V2'] = 'true'
os.environ['LANGCHAIN_ENDPOINT'] = 'https://api.smith.langchain.com'
os.environ['LANGCHAIN_API_KEY'] = 'My_LANGCHAIN_API_KEY'
os.environ['LANGCHAIN_PROJECT'] = 'default'

from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI()
llm.predict("Hello, world!")
`
response: Hello! How can I assist you today?

But langsmith can't capture any data and I didn't find errors anywhere.

PS: ALL my API_KEY is validate

**Comment by hinthornw** [comment]
Thanks for raising this issue! Could you please confirm:

- What langchain / langsmith version are you using?
- Is your API key your personal API key? or an organization API key? 

In. your collab notebook, try running the following:

```
from langsmith import Client

client = Client()

url = next(client.list_runs(project_name="default")).url
print(url)
```

If that works, then the traces are available, just a bit hard to discover!

**Comment by loopdeloop76** [comment]
Hi, I have the same problem. I can see no traces in the langsmith app.
Your code works, but the URL returns a 404 message, when I open it in the browser.

**Comment by rakeshsarma** [comment]
Hi, 
I too am facing this error

openai.api_key = os.getenv("OPENAI_API_KEY")
os.environ['OPENAI_API_KEY'] = os.getenv("OPENAI_API_KEY")
os.environ["LANGCHAIN_API_KEY"] = str(os.getenv("LANGCHAIN_API_KEY"))
os.environ["LANGCHAIN_TRACING_V2"]= "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_PROJECT"]= str(os.getenv("LANGCHAIN_PROJECT"))

Here's the stack trace
raise ls_utils.LangSmithConnectionError(
langsmith.utils.LangSmithConnectionError: Connection error caused failure to get http://localhost:1984/sessions  in LangSmith API. Please confirm your LANGCHAIN_ENDPOINT. ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=1984): Max retries exceeded with url: /sessions?limit=1&name=Little-Guy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc751dabb20>: Failed to establish a new connection: [Errno 61] Connection refused'))")

**Comment by hinthornw** [comment]
Hi @rakeshsarma it looks like you may be setting `LANGCHAIN_ENDPOINT` as `http://localhost:1984` someplace before this code. Could you confirm?

**Comment by rakeshsarma** [comment]
Hi @hinthornw ,
Thank you for the for the response.
This issue was solved. I didn't do anything. Langsmith started working after a few mins.

**Comment by hinthornw** [comment]
Going to close as stale for now. Let me know if you still have issues

**Comment by bufgix** [comment]
@hinthornw Hi, I'm facing the same issue right now. After I deleted my test project, it stopped tracing my chains

**Comment by FiliRezGelly** [comment]
Same problem, yesterday worked like a charm. Today it is not tracing anything :/

**Comment by leoschet** [comment]
Same issue here. I still see older traces in the project, but no new traces are collected

**Comment by FiliRezGelly** [comment]
> Same problem here, yesterday it was working like a charm. Today it is not tracing anything :/

Now is tracing them again. Problem solved for me

**Comment by Sulomus** [comment]
Unfortunetly for me the same issue. Out of nowhere langsmith stopped tracing chain calls 😞

**Comment by Daethyra** [comment]
I have traces from 40 minutes ago and now I can't get tracing to work.

**Comment by ariellasmo** [comment]
I resolved the problem by correcting the naming of my environment variables from 
`LANGSMITH_ENDPOINT` -> `LANGCHAIN_ENDPOINT`, etc.

**Comment by lekpeng** [comment]
Hello I encountered a similar issue, do make sure you load the env before running the langsmith client. 

```
from dotenv import load_dotenv
from langsmith import Client

load_dotenv()
client = Client()
```

**Comment by andrujuanoo** [comment]
I'm having a similar issue using list_runs from langsmith client

<img width="738" alt="Screenshot 2024-02-07 at 16 55 17" src="https://github.com/langchain-ai/langsmith-sdk/assets/51160185/473384fa-f3e5-4b7f-a03e-e316d39ecb21">

**Comment by fahmidme** [comment]
For me, the issue was my VSCode didn't pick up `.env` file changes without closing and reopening the terminal for some reason.

**Comment by lury** [comment]
for me it wasn't working when i've used it with vscode and ipynb file - i had to reopen the file and run the cells again and it's working fine.

**Comment by hinthornw** [comment]
If traces aren't showing and you also aren't seeing log errors like "failed to connect" or "failed to batch ingest", it is almost always because of environment misconfiguration.

The environment most have have tracing enabled (LANGSMITH_TRACING=true or LANGCHAIN_TRACING_V2=true - case sensitive) AND you must have your API key set.

Environment lookup is cached, so if you're working in a notebook and set the environment after already running LangChain/LangSmith tracing code, you will likely have to restart your kernel.

**Comment by Charikshith** [comment]
Langsmith is giving us:

KEEP THESE VALUES In. ".env" file

LANGSMITH_TRACING=true

LANGSMITH_ENDPOINT="https://api.smith.langchain.com"

LANGSMITH_API_KEY=<your-api-key>"

LANGSMITH PROJECT="pr-shadowy-twitter-91"

ΟΡΕΝΑΙ_API_KEY="<your-openai-apj-key>"

now load this file

from doteny import load dotenv

load dotenv(doteny path="path of file/enyoverride=True)

Then use this mapping for the tracing to work.

import os

os.environ["LANGCHAIN_API_KEY] = os.getenv("LANGSMITH_API_KEY")

os.environ['LANGCHAIN_TRACING_V2]= os.getenv("LANGSMITH_TRACING")

os.environ['LANGCHAIN_ENDPOINT']= os.getenv("LANGSMITH_ENDPOINT")

os environ LANGCHAIN_PROJECT]= str(os.getenv("LANGSMITH_PROJECT"))


Hope this helps

**Comment by martinobettucci** [comment]
For those who are stuck and lost in this very badly documented and chaotic framework, then you need to activate both:
```
LANGCHAIN_TRACING_V2=true
LANGCHAIN_TRACING=true
```

And also set all endpoints and keys with both the SMITH and GRAPH
```
LANGSMITH_ENDPOINT=https://api.smith.langchain.com
LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
LANGCHAIN_API_KEY=lsv2_sk_4.....3
LANGSMITH_API_KEY=lsv2_sk_4.....3
LANGCHAIN_PROJECT=test
```

Why? who knows..
You're welcome @shib07-AIML @lury @Daethyra @leoschet @FiliRezGelly @bufgix @rakeshsarma

**Comment by rizese** [comment]
For folks using Python: if you're codebase is like mine, most of your env variables which are booleans will be `True` or `False` - it's important that `LANGCHAIN_TRACING_V2` is set to `true`! it's case sensitive! 

```
# bad
LANGCHAIN_TRACING_V2=True
#                    ↑

# good
LANGCHAIN_TRACING_V2=true
```

**Comment by sepet7508** [comment]
I followed @martinobettucci article, but it is not working. poor Langsmith

**Comment by BlueTurtle121** [comment]
If it's any help, the fix for me was changing

$env:LANGSMITH_TRACING='True'

to

$env:LANGSMITH_TRACING='true'

**Comment by vineet-kumar59** [comment]
> My advice to everyone , if you are working on VS code and using .env property file then after update the properties values just restart your vs code and try , it will work
> 
> I tried 50 times it didn't work but did above activity on 51th time , it worked. :-)

This worked for me ,Thank You

**Comment by shividwivedi** [comment]
i am facing same issue , i cannot trace even my simple ChatOpenAI response !
LANGSMITH_TRACING=true

LANGSMITH_ENDPOINT="https://api.smith.langchain.com/"

LANGSMITH_API_KEY="

LANGSMITH PROJECT="multiagent_colloboration"

ΟΡΕΝΑΙ_API_KEY=""

**Comment by apoorvasj** [comment]
I also faced this issue. What finally worked for me was-
In .env file specifying the following (exactly as it is given under tracing projects when you click create new project):
Also I used HuggingFace. 

I am using VSCode and .ipynb files.

In .env-
<code>
LANGCHAIN_TRACING_V2=true
LANGSMITH_TRACING = true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGSMITH_API_KEY="your_api_key"
LANGSMITH_PROJECT="your_project_name"
HF_TOKEN="your_hugging_face_token"  #Remove this HF_TOKEN and replace it with the API key you are using (if any).
</code>

After saving these in .env it is better to close and open VSCode or activate/deactivate virtual environment.

Make sure to use <code> load_dotenv() </code> in your program to load all environment variables and then on invoking your LLM, you should be able to view the traces on LangSmith.

**Comment by venkatareddykonasani** [comment]
This worked for me on Colab
```python
from langsmith import utils
utils.get_env_var.cache_clear()
```
