### ISSUE TITLE
Issue: `list_runs` does not include tokens for each run.

### ISSUE THREAD

**Issue by homanp** [langchain-ai/langsmith-sdk#218]
### Issue you'd like to raise.

The `list_runs` method doesn't provide the tokens in the API response for each given run even though the `Pydantic` response schema has it listed. 

```
output = langsmith_client.list_runs(
    project_id="5b5b88d3-af77-4a64-9607-51782ac7a62f",
    filter=f"has(tags, '{agent_id}')",
)
```

OS info:
```
LangChain Environment:
sdk_version           : 0.0.26
library               : langsmith
platform              : macOS-13.3-arm64-arm-64bit
runtime               : python
runtime_version       : 3.11.4
langchain_version     : 0.0.285
docker_version        : Docker version 24.0.5, build ced0996
docker_compose_command: docker compose
docker_compose_version: Docker Compose version v2.20.2-desktop.1
```

### Suggestion:

Return all available fields for available for each `run` in both `list` and `get` methods of the sdk

**Comment by hinthornw** [comment]
@homanp the top level field was added in 0.0.33 - it should be retrievable if you update your installed version!

It should still be visible in the `extra` field in your version, however

**Comment by hinthornw** [comment]
As an aside - there are a couple async tasks that occur between the time when a run is first logged and when the root run has all its tokens counted and  available, so if the run was logged in the last minute or so, the token counts may note be available or fully up to date. You can check with a query like the following:

```
from datetime import datetime, timedelta

# Hour ago
end_time = datetime.now() - timedelta(hours=1)
next(client.list_runs(
    project_id="f53ccf51-57c1-4c97-afdf-7ca5569945cd",
    end_time=end_time
)).total_tokens
```

**Comment by hinthornw** [comment]
LMK if it still gives you issues!

**Comment by homanp** [comment]
> LMK if it still gives you issues!

Works! Closing issue!
