### ISSUE TITLE
LangSmith without LangChain imports Fail

### ISSUE THREAD

**Issue by chasemcdo** [langchain-ai/langsmith-sdk#273]
### Issue you'd like to raise.

When running the LangSmith without LangChain Hello World example for TypeScript I get to following error when trying to import the required components.

```
Module '"langsmith"' has no exported member 'RunTreeConfig'.
```

### Suggestion:

Fix imports as seen in:
- #272

**Comment by hinthornw** [comment]
Thank you for the fix :)

**Comment by chasemcdo** [comment]
Probably not the correct spot for this, but is there a schedule for new releases of LangSmith? Have used it through LangChain before and am eager to use it in our non-LangChain integrated services :)
