### ISSUE TITLE
Issue: Run Count and Total Tokens not updating

### ISSUE THREAD

**Issue by EliasGit2017** [langchain-ai/langsmith-sdk#281]
### Issue you'd like to raise.

After a few hours, the number of runs and the token count stopped increasing in all my apps. New requests are being traced correctly and perfectly (langsmith is really helpful, I don't think I can use something else).
This might be caused by the fact that the `0.0.56` was released in the meantime.
Still after updating, I see no changes on the run & tokens count.
Any Idea about where this might come from ?
Thank you

**Comment by hinthornw** [comment]
Hi @EliasGit2017 thank you for raising. We had to temporarily pause aggregations like token counts to make some large infrastructure improvements and better scale to support all our users. We hope to resume this functionality this weekend

**Comment by EliasGit2017** [comment]
Makes sense, thank you and good luck with the improvements 👍🏻

**Comment by zyz9074** [comment]
Why is the Total Tokens in the project on my Langsmith still not updating?
