### ISSUE TITLE
Issue: LANGSMITH API KEY access request

### ISSUE THREAD

**Issue by dobahoang** [langchain-ai/langsmith-sdk#297]
### Issue you'd like to raise.

Hello development team, I hope this message can reach you. I took a look at the features Langsmith brings to the community, it's amazing. That's the solution my team needs. I hope I can access it, but I can't find my API key. Can you help me?Please.
Email: dbhoang@tma.com.vn

**Comment by hinthornw** [comment]
Hi @dobahoang , could you send an email to support@langchain.dev to be unblocked? Thank you!

**Comment by hinthornw** [comment]
Will close this issue :)
