### ISSUE TITLE
Issue: Tokens calculation does not work properly with gpt4-vision

### ISSUE THREAD

**Issue by luca-medeiros** [langchain-ai/langsmith-sdk#306]
### Issue you'd like to raise.

Using gpt-4-vision-preview with smith generates wrong token values. Using base64 encoding
![image](https://github.com/langchain-ai/langsmith-sdk/assets/67411094/64d7f36f-562a-40a7-8ddb-2e98863a414f)

### Suggestion:

Calculate text and image tokens separately. Maybe complex for images so could accept user input for image dimensions.

**Comment by hinthornw** [comment]
Thanks for raising! A fix should be coming out in the next version of langchain and langsmith

**Comment by luca-medeiros** [comment]
Cheers!
