### ISSUE TITLE
Bulk Deletion of Test Runs

### ISSUE THREAD

**Issue by chasemcdo** [langchain-ai/langsmith-sdk#312]
### Feature request

If you have selected multiple test runs it would be great if there was an option to bulk delete them rather than having to do it individually.

The popup at the bottom seems like a great place to fit in the new button.
<img width="1452" alt="image" src="https://github.com/langchain-ai/langsmith-sdk/assets/74692158/7b0ed27e-d791-4269-9efd-3a76e0f5c8ca">

### Motivation

As a user iterating on test cases within LangSmith, I often get several erroneous runs which aren't of much use to keep for comparison. The addition of this feature would enable quicker management of test runs.

**Comment by hinthornw** [comment]
Thanks for the request, @chasemcdo ! We're planning to implement this soon

**Comment by hinthornw** [comment]
This is now implemented. Thanks for the request!
<img width="1140" alt="image" src="https://github.com/langchain-ai/langsmith-sdk/assets/13333726/662a0202-39c4-4fb1-847e-85188b484e83">

**Comment by klsdjft** [comment]
> Hi @hinthornw,
> 
> I've recently started using Langsmith and noticed that I can't delete or move runs from one project to another in the dashboard. I am wondering if Langsmith supports these actions right now and if so, could you provide instructions on how to perform them?
> 
> Thank you so much! ![Screenshot 2024-07-15 at 11 14 38 AM](https://private-user-images.githubusercontent.com/85110830/348796286-df3b3285-50ae-4adb-a86b-7ebd3e2e830b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDA5MDUsIm5iZiI6MTcyMTIwMDYwNSwicGF0aCI6Ii84NTExMDgzMC8zNDg3OTYyODYtZGYzYjMyODUtNTBhZS00YWRiLWE4NmItN2ViZDNlMmU4MzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA3MTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNGViZjFiMzI4NGRmOTgxZDExMTFhZTZkMzRjZGUwNDhiMWJjMjc5NzA3NTBjMTZiOTgzMzFlNzZhMTQxYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mx-4yS6aIgBnsLRc3HolqTM36vc-xT7H-vUaQRse04M)

I guess the problems is: Experiment can be delete, but Traces/Runs can not. When I delete Experiment, the run belong with experiment is not deleted. 

I'am also finding where to delete trace/run, except delete all project.

**Comment by aaricantto** [comment]
Yes, I too wish to be able to delete Traces/Runs while I'm testing projects! This feature would be awesome

![image](https://github.com/user-attachments/assets/ac3a2db2-884e-4711-927c-9029e4e8cc0f)

**Comment by wpm** [comment]
LangSmith is a non-starter for my organization without the ability to delete runs. Some of our data is proprietary and sensitive. If by an accident on our part some of it ends up on a public LangSmith server, we have to be able to delete it immediately.

Right now my recommendation to my organization is to stay away from LangSmith. It's too easy to make a mistake. We'll probably have dev ops block all LangSmith servers just to be on the safe side.

Otherwise we like LangChain/LangGraph, but this is a huge problem for us.
