### ISSUE TITLE
Issue: Getting an error Licence key is not valid

### ISSUE THREAD

**Issue by sushantgo** [langchain-ai/langsmith-sdk#315]
### Issue you'd like to raise.

Hi Team,
We are using langsmith to create and test LLM applications internally but while running docker.yml file below error - 
**Exception: License key is not valid**

In a docker file we are not passing any license key. it was working previously but from last 2-3 days its not working.
We are running docker images locally and its self hosted langsmith.
can someone please provide some inputs how to  fix the error.

**Error Image -** 
![langsmith-error](https://github.com/langchain-ai/langsmith-sdk/assets/152602076/a18553f0-fe77-4c21-95ba-2bf8a05d75d3)

**Comment by hinthornw** [comment]
Hi @sushantgo , thanks for the note! We require a license key for self-hosted LangSmith. If you haven't already, could you contact support@langchain.dev? Thanks for your patience!
