### ISSUE TITLE
Issue: Langsmith is not working with the gpt-4-preview model

### ISSUE THREAD

**Issue by SurabhiKadam** [langchain-ai/langsmith-sdk#321]
### Issue you'd like to raise.

I am calling llm by sending POST request to the OpenAI API endpoint "https://api.openai.com/v1/chat/completions" using the gpt-4-1106-preview model. I am correctly connecting langsmith to my code. but when the llm call is made using the post request the langsmith does not reflect the post request. Could you help me with this?

**Comment by hinthornw** [comment]
Hi @SurabhiKadam , are you saying you're using the `requests` library directly (or something similar)? 

For tracing to be connected, you'll have to wrap your call in the `traceable` decorator, or manually manage the span event there. See the following for an example

https://docs.smith.langchain.com/cookbook/tracing-examples/traceable

**Comment by hinthornw** [comment]
Feel free to re-open if you're still having issues with langsmith
