### ISSUE TITLE
Issue: Self hosted can't find the API

### ISSUE THREAD

**Issue by mrcmoresi** [langchain-ai/langsmith-sdk#323]
### Issue you'd like to raise.

Hi everyone, 

I trying to self host langsmith, I installed the package version 0.0.69, and then ran 

langsmith start

It's running in a VM in azure cloud, I opened all the ports just to be sure there is no error there. also, there is no active firewall 
Docker looks like this
![image](https://github.com/langchain-ai/langsmith-sdk/assets/12852824/de3f8f1f-99e3-4e02-903c-08f41ac7efcb)

At the moment of opening it can't find the api
![image](https://github.com/langchain-ai/langsmith-sdk/assets/12852824/74e78087-ad23-4d24-bba6-66bc9b9c8fe5)

any idea how can i continue?

**Comment by schottenstein** [comment]
Hi @mrcmoresi - Self-hosting LangSmith needs a license key. In order to get one, you need to have an annual, enterprise contract. If you're interested in learning more you can reach out to sales@langchain.dev.
