### ISSUE TITLE
Get Feedback comments from LangSmith

### ISSUE THREAD

**Issue by jannikjw-sai** [langchain-ai/langsmith-sdk#325]
### Feature request

When calling `list_runs()` from the client, only the feedback scores are returned, but not the comments. The `feedback_stats` should also contain the feedback comment.

### Motivation

I want to run text analysis and easily display all the runs that have negative feedback.

**Comment by hinthornw** [comment]
You can call `client.list_feedback()` with the run id to get the full feedback info

**Comment by hinthornw** [comment]
@jannikjw-sai I'm going to close this out, unless you have a different question
