### ISSUE TITLE
Allow name customization for LLM Objects

### ISSUE THREAD

**Issue by abhagsain** [langchain-ai/langsmith-sdk#329]
### Feature request

Allow name customization for LLM Objects of each run

### Motivation

Right now, name customization is only supported for LLMChain, but LLMChain doesn't support `.generate,` which makes parallel calls and returns rich outputs. 
For our use case, each trace has multiple LLM (object) calls, and it gets confusing in the UI to identify each call, and we have to click through all the items to find the needed call. The custom name would make it much easier.

**Comment by hinthornw** [comment]
Will add to our TODOs
