### ISSUE TITLE
DOC: the @traceable decorator docs example not working

### ISSUE THREAD

**Issue by zozoheir** [langchain-ai/langsmith-sdk#332]
### Issue with current documentation:

The script below, taken from the [documentation page](https://docs.smith.langchain.com/cookbook/tracing-examples/traceable) does not trace anything to my langsmith project. I have created a new api key but nothing seems to work. 

```python

import os
from datetime import datetime
from typing import List, Optional, Tuple

import openai

openai.api_key = os.environ['OPENAI_API_KEY']
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_API_KEY"] = ""
os.environ["LANGCHAIN_PROJECT"] = ""


from langsmith.run_helpers import traceable

# We will label this function as an 'llm' call to better organize it
@traceable(run_type="llm")
def call_openai(
    messages: List[dict], model: str = "gpt-3.5-turbo", temperature: float = 0.0
) -> str:
    return openai.chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature,
    )


# The 'chain' run_type can correspond to any function and is the most common
@traceable(run_type="chain")
def argument_generator(query: str, additional_description: str = "") -> str:
    return (
        call_openai(
            [
                {
                    "role": "system",
                    "content": f"You are a debater making an argument on a topic."
                    f"{additional_description}"
                    f" The current time is {datetime.now()}",
                },
                {"role": "user", "content": f"The discussion topic is {query}"},
            ]
        )
        .choices[0]
        .message.content
    )


@traceable(run_type="chain")
def critic(argument: str) -> str:
    return (
        call_openai(
            [
                {
                    "role": "system",
                    "content": f"You are a critic."
                    "\nWhat unresolved questions or criticism do you have after reading the following argument?"
                    "Provide a concise summary of your feedback.",
                },
                {"role": "system", "content": argument},
            ]
        )
        .choices[0]
        .message.content
    )


@traceable(run_type="chain")
def refiner(
    query: str, additional_description: str, current_arg: str, criticism: str
) -> str:
    return (
        call_openai(
            [
                {
                    "role": "system",
                    "content": f"You are a debater making an argument on a topic."
                    f"{additional_description}"
                    f" The current time is {datetime.now()}",
                },
                {"role": "user", "content": f"The discussion topic is {query}"},
                {"role": "assistant", "content": current_arg},
                {"role": "user", "content": criticism},
                {
                    "role": "system",
                    "content": "Please generate a new argument that incorporates the feedback from the user.",
                },
            ]
        )
        .choices[0]
        .message.content
    )


@traceable(run_type="chain")
def argument_chain(query: str, additional_description: str = "") -> str:
    argument = argument_generator(query, additional_description)
    criticism = critic(argument)
    return refiner(query, additional_description, argument, criticism)


result = argument_chain(
    "Whether sunshine is good for you.",
    additional_description="Provide a concise, few sentence argument on why sunshine is good for you.",
)
print(result)
```

**Comment by hinthornw** [comment]
The platform is being slow right now as we make an infra upgrade. Thanks for your patience. Have  the traces populated yet?

**Comment by zozoheir** [comment]
It doesn't seem like langfuse or langsmith are production ready. Do these issues happen often?

**Comment by hinthornw** [comment]
LangSmith is still in beta. We do have thousands of prod users at present, but we have to complete these infra upgrades before we can start making the type of SLAs I think you're hinting at (outside of our enterprise offerings).

**Comment by zozoheir** [comment]
> LangSmith is still in beta. We do have thousands of prod users at present, but we have to complete these infra upgrades before we can start making the type of SLAs I think you're hinting at (outside of our enterprise offerings).
> 
> As for LangFuse, I can't comment. They're not affiliated with LangChain but seem to have drawn a lot of inspiration from what we have built

Oh sorry I meant 'langchain' not 'langfuse'. I just corrected the comment.

**Comment by hinthornw** [comment]
Hm ok - rumorz looks great btw! congrats - lmk if you have any other pointers or questions. The last ~2 weeks have been the most flakey LangSmith has been since we launched due to a confluence of factors so hopefully won't get this bad again

**Comment by zozoheir** [comment]
> Hm ok - rumorz looks great btw! congrats - lmk if you have any other pointers or questions. The last ~2 weeks have been the most flakey LangSmith has been since we launched due to a confluence of factors so hopefully won't get this bad again. On the LangChain side we have split out the core library and are further separating out ecosystem packages to make the core API more clear, but if there's anything you'd like us to improve, we're open to feedback

Thank you! I haven't launched rumorz yet but getting ready for launch as we speak. This is mainly for my LLM library https://github.com/zozoheir/tinyllm  - > Which I am using for building Rumorz

**Comment by hinthornw** [comment]
Well in any case, I'll do my best to fix issues if they'd help you. In the meanwhile I'm going to close out this ticket since those queueing were resolved
