### ISSUE TITLE
Issue: Tags aren't properly sanitized

### ISSUE THREAD

**Issue by arnob-sengupta** [langchain-ai/langsmith-sdk#381]
### Issue you'd like to raise.

We have tags `['<name>','openai-functions']`

this should be rendered as two tags:
![image](https://github.com/langchain-ai/langsmith-sdk/assets/74873878/4d115af1-8386-4b1d-85ff-a3e14d637bda)

but if there is a `'` in the name tag, for example, it is rendered as a single tag
![image](https://github.com/langchain-ai/langsmith-sdk/assets/74873878/2572cefe-50de-4989-af92-89653dd2e832)

Another example in monitor actually breaking functionaity:
![Untitled](https://github.com/langchain-ai/langsmith-sdk/assets/74873878/7edc71ae-e02b-4574-8c75-10af1f74d7d6)
the last tag concats `O'Connor` with other users and is unclickable

### Suggestion:

Sanitize/escape characters like `'` properly

**Comment by hinthornw** [comment]
We've identified an issue with our DB and are working on a fix: https://github.com/maximdanilchenko/aiochclient/issues/112.

**Comment by hinthornw** [comment]
Should be fixed now. Let me know if you are still seeing issues!
