### ISSUE TITLE
DOC: Quick Start Guide with Typescript while passing explicit keys has a typeerror.

### ISSUE THREAD

**Issue by JadenSWang** [langchain-ai/langsmith-sdk#400]
### Issue with current documentation:

If you follow the steps here: https://docs.smith.langchain.com/ and attempt to "run the example code below" you will get a typeerror on the tracer part of:  `await model.invoke("Hello, world!", { callbacks: [tracer] })`.

### Idea or request for content:

I'm not sure if this is a user error or documentation error but I for the life of me cannot figure out why I'm getting a: 

```
Type 'LangChainTracer' is not assignable to type 'BaseCallbackHandler | BaseCallbackHandlerMethodsClass'.
  Property 'lc_id' is missing in type 'LangChainTracer' but required in type 'BaseCallbackHandler'.ts(2322)
```

**Comment by JadenSWang** [comment]
turns out you can ts-ignore the error and it works, scary scary

**Comment by hinthornw** [comment]
Could you see if this helps? https://js.langchain.com/docs/get_started/installation#installing-integration-packages

It may be that you have two different versions of langchain core

**Comment by JadenSWang** [comment]
That did the trick, I removed everything and just ran `pnpm i langchain` (no core, no community) and everything seems be working fine
