### ISSUE TITLE
Issue: Langsmith default project hidden unless you sort by name

### ISSUE THREAD

**Issue by JadenSWang** [langchain-ai/langsmith-sdk#401]
### Issue you'd like to raise.

Steps:

- go to langsmith main dashboard
- click on projects (if its an empty org you should see 1 project on this button)

At this point you won't see any projects (you have a default one hidden)

- click on the table header where you can change the direction of sorting by name, either A-Z or Z-A

Here, you will see "default" come up. This is a little confusing because the documentation references: `export LANGCHAIN_PROJECT=<your-project>  # if not specified, defaults to "default"` in https://docs.smith.langchain.com/

**Comment by hinthornw** [comment]
An improvement to this will be included in one of the next releases

**Comment by hinthornw** [comment]
Going to close this as fixed.
