### ISSUE TITLE
Request to add cost tracking 

### ISSUE THREAD

**Issue by SoulEvill** [langchain-ai/langsmith-sdk#402]
### Feature request

cost is not easy to track with current langsmith especially when using different llm and llm provider

### Motivation

I am always frustrated to track the cost

**Comment by hinthornw** [comment]
Cost tracking was added today. LMK what you think!

**Comment by SoulEvill** [comment]
@hinthornw thanks for adding it! I've compared few open ai api call - gpt4 and gpt4 turbo cost are spot on. but gpt3.5 seems off

according to openai api pricing: (https://openai.com/pricing)

gpt-3.5-turbo-0125 | $0.0005 / 1K tokens | $0.0015 / 1K tokens

and I have 2489 input and 319 output  it should come down to 2489*0.0005/1000 + 319*0.0015/1000 = 0.001743

But on langsmith UI it was displayed 0.00043715

please see it here: https://smith.langchain.com/public/dce3fb64-3dfa-4111-9a0f-0556d989b7fe/r
