### ISSUE TITLE
Find nested chains when filtering

### ISSUE THREAD

**Issue by ElianBelot** [langchain-ai/langsmith-sdk#450]
### Feature request

Allow users to find nested chains by filtering for them.

### Motivation

If we want to filter a trace by name, it has to either be:
- A top-level chain that can be found in the "Traces" tab
- An LLM call that can be found in the "LLM calls" tab

Currently, if we have `ChainA -> ChainB -> LLMCall` we can only filter for `ChainA` or `LLMCall` and we'll have a "No results found." when filtering for `eq(name, "ChainB")` in either tab.

**Comment by hinthornw** [comment]
Adding in a future release

**Comment by hinthornw** [comment]
@ElianBelot it's supported now FYI via the trace_filter and tree_filter

**Comment by ElianBelot** [comment]
Thank you!
