### ISSUE TITLE
Completed traces locked/frozen in pending status. Option to delete individual traces?

### ISSUE THREAD

**Issue by tgram-3D** [langchain-ai/langsmith-sdk#453]
I just started using LangSmith, and it's awesome, but certain traces are locking up in "pending" status even after they complete successfully. It's happening on runs with higher concurrency parameters/more nested runs. Is this something you've run into before? 

Also, there doesn't seem to be an option to delete individual traces from a project, so to clear these pending "lock ups" I have to delete and recreate the whole project. Could deleting traces maybe be a future feature request?

**Comment by hinthornw** [comment]
What version of langsmith are you using?

(and langchain, if you're using this)

**Comment by tgram-3D** [comment]
@hinthornw I haven't updated anything since last week, I think. Current versions are langchain 0.1.5 and langsmith 0.0.87. Another thing I noticed is if I did a keyboard interrupt on a run and it also froze in pending status. I will do an update on Monday.

**Comment by hinthornw** [comment]
We fixed a couple issues with pending runs in more recent versions. Could you let me know if the issue persists after upgrading?

**Comment by vishal-git** [comment]
> What version of langsmith are you using?
> 
> (and langchain, if you're using this)

I am having the same issue. Several runs and traces are frozen in "pending" status. The status hasn't changed even after a couple of days.

Here's the version info:

```
 name         : langsmith
 version      : 0.1.5
 description  : Client library to connect to the LangSmith LLM Tracing and Evaluation Platform.

dependencies
 - pydantic >=1,<3
 - requests >=2,<3

required by
 - langchain >=0.1.0,<0.2.0
 - langchain-community >=0.1.0,<0.2.0
 - langchain-core >=0.1.0,<0.2.0
```

And,

```
 name         : langchain
 version      : 0.1.9
 description  : Building applications with LLMs through composability

dependencies
 - aiohttp >=3.8.3,<4.0.0
 - dataclasses-json >=0.5.7,<0.7
 - jsonpatch >=1.33,<2.0
 - langchain-community >=0.0.21,<0.1
 - langchain-core >=0.1.26,<0.2
 - langsmith >=0.1.0,<0.2.0
 - numpy >=1,<2
 - pydantic >=1,<3
 - PyYAML >=5.3
 - requests >=2,<3
 - SQLAlchemy >=1.4,<3
 - tenacity >=8.1.0,<9.0.0

required by
 - ragas *
```

**Comment by hinthornw** [comment]
@vishal-git this is because the span end never made it to the server. they will never be marked finished unless they are patched with an end time.

**Comment by vishal-git** [comment]
Okay, that makes sense. Thank you for replying.

Can you please advise how to set an end time to avoid this situation? This is happening way too often and we are stuck with so many traces (and runs) in 'pending' mode.

**Comment by snlamm** [comment]
I'm running into a similar issue as well, even using the latest version of node.js langsmith - 0.1.8.
Chains get stuck in pending state (even as they successfully complete). For longer chains, children runs stop being logged after the chain reaches a larger size.

**Comment by snlamm** [comment]
if it's helpful, I'm also seeing plenty of these error logs (I'm not sure if they can be safely ignored or not):
```
Error in handler CustomLangChainTracer, handleChainEnd: Error: Failed to update run: 409 Conflict {"detail":"Payloads already received"}
```

**Comment by hinthornw** [comment]
What version of langsmith are you?

**Comment by snlamm** [comment]
@hinthornw thanks for checking back! for me, this has since resolved

**Comment by snlamm** [comment]
though, if it's helpful,  I'm still seeing the `Error in handler LangChainTracer, handleChainEnd: Error: Failed to update run: 409 Conflict {"detail":"Payloads already received"}` when using node.js langgraph (v0.0.10) with langsmith (v0.1.8)

**Comment by athmedata** [comment]
I am getting similar pending RunnableSequence issue with langsmith 0.1.38, but this time with this error 

Failed to batch ingest runs: LangSmithError('Failed to post https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'422 Client Error: unknown for url: https://api.smith.langchain.com/runs/batch\', \'{"detail":"start_time must be an ISO 8601 timestamp"}\')')

**Comment by AyatKhraisat** [comment]
I have similar issue 

Failed to batch ingest runs: LangSmithConnectionError('Connection error caused failure to post https://api.smith.langchain.com/runs/batch  in LangSmith API. Please confirm your LANGCHAIN_ENDPOINT. ConnectionError(MaxRetryError("HTTPSConnectionPool(host=\'api.smith.langchain.com\', port=443): Max retries exceeded with url: /runs/batch (Caused by ProtocolError(\'Connection aborted.\', timeout(\'The write operation timed out\')))"))')

**Comment by sergiovadyen** [comment]
I have a similar issue:

`Failed to batch ingest runs: LangSmithError('Failed to post https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'422 Client Error: unknown for url: https://api.smith.langchain.com/runs/batch\', \'{"detail":"start_time must be an ISO 8601 timestamp"}\')')`

**Comment by hinthornw** [comment]
Thank you all for your patience. @sergiovadyen and @thmedata do you have a code snippet I can use to reproduce your 422's? 


`422`  is a bit different than a connection error, which is potentially different from the `409` errors. The latter two are possibly related though.

**Comment by athmedata** [comment]
@hinthornw 
I use langsmith with langchain 

by just calling 

`langsmith_client = langsmith.Client()`

the error happened after I upgraded the Langsmith package

**Comment by hinthornw** [comment]
@athmedata that sounds like an unrelted error, probably related to API keys?

**Comment by athmedata** [comment]
@hinthornw 
I don't think it is related to API keys because I work with 2 environments with 2 versions of Langsmith, and the updated version only has the problem start_time timestamp issue

**Comment by RobertCorwin-AustinAI** [comment]
This is still happening for us but only after upgrading to 0.2.6 from 0.0.333:   Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'422 Client Error: unknown for url: https://api.smith.langchain.com/runs/batch\', \'{"detail":"start_time must be an ISO 8601 timestamp"}\')')

same API keys, etc.  LangSmith version 0.1.82

**Comment by hinthornw** [comment]
@RobertCorwin-AustinAI could you share a code snippet to help us debug?

Pending runs occur when the run patch event doesn't make it to the server. The reason for that is usually connectivity or rate limiting related, but in this case it seems like some issue with how the timestamp is being passed to the client.

I'm having a hard time reproducing this particular case.

**Comment by RobertCorwin-AustinAI** [comment]
I know you'll hate hearing this but it appears to happen at random...  although we're using an agent and also a chain in a tool and it doesn't seem to happen for the "AgentExecutor" but it does happen in the "Runnable Sequence" which involves calling parallel search functions - RunnableParallel.  maybe the parallelism has something to do with it?  Is there some way we can monitor the actual calls to the LangSmith API?  It seems to me that might help a lot.  I actually tried to do that using a packet sniffer on my network card but it was taking too much time.  Is there some way to log the actual calls in a verbose debug mode or something?  thx

**Comment by hinthornw** [comment]
Going to close as stale and likely overlapping with https://github.com/langchain-ai/langsmith-sdk/issues/808
