### ISSUE TITLE
Issue: Azure Provisioned Throughput and Cost Tracking

### ISSUE THREAD

**Issue by elliotmrodriguez** [langchain-ai/langsmith-sdk#520]
### Issue you'd like to raise.

Hello again, not an issue but rather a question. 

Azure is gating access to gpt-3.5-turbo-0125 and 1106 behind a requirement to have purchased Provisioned Throughput Units (PTUs). This means that for pay-as-you-go, the models that are considered legacy (0613, 0301) are the only ones supported. Similar constraints are going to be in place, if they aren't already, for Bedrock model access. 

Is the provisioned throughput model a supported use case OOTB by LangSmith?

**Comment by hinthornw** [comment]
Are you asking about whether it's supported in the playground or whether we do cost analytics that is specifically geared around PTU setups? Or something else?

**Comment by chaosGuppy** [comment]
Any hints as to how one can customise this?

**Comment by hinthornw** [comment]
Much delayed (sorry!), but for future readers:

https://docs.smith.langchain.com/how_to_guides/tracing/log_llm_trace

and

https://docs.smith.langchain.com/how_to_guides/tracing/calculate_token_based_costs
