### ISSUE TITLE
Issue: Agent created with `create_react_agent` always shows Error in Langsmith Trace even though working fine

### ISSUE THREAD

**Issue by dentro-innovation** [langchain-ai/langsmith-sdk#522]
### Issue you'd like to raise.

I'm trying out the new way to create react agents, I took all the code apart from the tools and the ChatModel from these docs:
https://python.langchain.com/docs/modules/agents/agent_types/react

The toolkit I use is the Playwright Browser toolkit, the ChatModel is Mistral Medium and Small.

1. The agent performs this way much better than the old way when I used `initialize_agent`
2. Even though it performs better and works fine, the trace in Langsmith always shows an error, as if the run failed:
![image](https://github.com/langchain-ai/langsmith-sdk/assets/135163019/b295a16e-3f9c-4f77-bfc4-6f2be7e5cb83)

The error: `ValueError('An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass `handle_parsing_errors=True` to the AgentExecutor. This is the error: Parsing LLM output produced both a final answer and a parse-able action`.

My output looks fine and parseable like a final answer should look like.

The traces logged when the previous agent created via `initialize_agent` was used were all fine.

### Suggestion:

Successful logs of the traces in langsmith when using the new `create_react_agent` agent according to the docs.

**Comment by dentro-innovation** [comment]
Ok if I add `handle_parsing_errors=True` to the AgentExecutor everything works fine. Not sure if it's supposed to only work with handling parsing errors, but you guys can close the issue if you think everything is as it should be.

**Comment by hinthornw** [comment]
hmm - it seems the agent is handling the errors at some point, and we show an error at the top if there are errors anywhere in the trace

**Comment by hinthornw** [comment]
Feel free to re-open if the issue persists!
