### ISSUE TITLE
Failed to batch ingest runs: LangSmithError("Failed to post .../runs/batch in LangSmith API. Invalid URL '.../runs/batch': No scheme supplied. Perhaps you meant https://.../runs/batch?\n")

### ISSUE THREAD

**Issue by dds-normous** [langchain-ai/langsmith-sdk#528]
Hi,
I am having this issue with a URL API call to LangSmith API.
Here is some of the terminal results (which repeats every 180 seconds).

Checking for new emails
Failed to batch ingest runs: LangSmithError("Failed to post .../runs/batch in LangSmith API. Invalid URL '.../runs/batch': No scheme supplied. Perhaps you meant https://.../runs/batch?\n")

No new emails
Waiting for 180 seconds
Failed to batch ingest runs: LangSmithError("Failed to post .../runs/batch in LangSmith API. Invalid URL '.../runs/batch': No scheme supplied. Perhaps you meant https://.../runs/batch?\n")

I had chatgpt check the .py files of the application, and it can't locate the possible URL issue.
It's response was:

Understanding the Error
Invalid URL: The program is trying to make a web request to an API endpoint, but the URL it's using is incomplete or malformed because it lacks the scheme (http:// or https://).
LangSmithError: This is a custom error, likely defined in your CrewAI application or a dependency, indicating an issue specifically with LangSmith API interactions.
Suggested Fix: The error message even hints at a possible solution: ensuring the URL starts with https://.

Thanks for your help!

**Comment by dds-normous** [comment]
As a follow-up,  I am running crewAI's example of the gmail inbox management within the CrewAI-LangGraph folder.

**Comment by hinthornw** [comment]
It looks like you have set
```
LANGCHAIN_ENDPIONT="..."
```
Or something similar?

**Comment by sorydi3** [comment]
I'm having the same issue as well.

I have the following variables in my .env file 
`LANGCHAIN_TRACING_V2="true"
LANGCHAIN_API_KEY="ls__xxxdxxxxx555096736"
LANGCHAIN_ENDPOINT= "https://api.smith.langchain.com"`

and this is the error I'm getting back.

![image](https://github.com/langchain-ai/langsmith-sdk/assets/19431081/2ea5db38-0faa-4bbf-9ac9-4c4a90fadb0f)

it say that the key is invalid , and have literally copied the key from the langsmith site and pasted to my .env file.

**Comment by dds-normous** [comment]
Hi, 
Thanks for all the replies. I am using the crewAI-examples, specifically the CrewAI- LangGraph program that checks for new gmails and write email reply drafts. 
https://github.com/joaomdmoura/crewAI-examples.git

I didn't enter any of the optional Langchain .env items, but entered my OpenAI and Tavily API keys.

# Optional
LANGCHAIN_TRACING_V2=...
LANGCHAIN_ENDPOINT=...
LANGCHAIN_API_KEY=...
LANGCHAIN_PROJECT=...

I was setting up and running the program based on this youtube video:
I use AI Agents to Respond to my Emails. Integrate CrewAI + LangGraph
https://www.youtube.com/watch?v=0SYyxNHlAWQ&t=261s

**Comment by AbubakrChan** [comment]
did you found any solution yet?

**Comment by praveen-k-Soni** [comment]
Hi, were you able to find a solution to this issue- i have the exact same issue and was following the same youtube tutorial- Currently stuck :( ... any help will be greatly appreciated.
