### ISSUE TITLE
Issue: Unable to collect run ID using callbacks.collect_run()

### ISSUE THREAD

**Issue by chip-davis** [langchain-ai/langsmith-sdk#530]
### Issue you'd like to raise.

Hello, trying to follow the docs to retreive a run id from a chain so that I can implement feedback on my front-end. I am using langgraph and tracing (just the default stuff) works great. I followed the docs linked [here](https://docs.smith.langchain.com/tracing/faq/langchain_specific_guides) as well as the information in issue #187. 
Here is my implementation:
```
def generate(self, state):
        """
        Generate answer

        Args:
            state (dict): The current graph state

        Returns:
            state (dict): New key added to state, generation, that contains LLM generation
        """
        print("---GENERATE---")
        state_dict = state["keys"]
        question = state_dict["question"]
        documents = state_dict["documents"]

        # Prompt
        prompt = hub.pull("rlm/rag-prompt")

        # LLM
        if self.run_local == "Yes":
            llm = ChatOllama(model=self.local_llm, temperature=0)
        else:
            llm = AzureChatOpenAI(
                openai_api_version="2023-05-15",
                azure_deployment="chat",
                api_key=os.getenv("AZURE_OPENAI_KEY"),
                azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
            )

        # Chain
        rag_chain = prompt | llm | StrOutputParser()

        # Run
        with callbacks.collect_runs() as cb:
            generation = rag_chain.invoke({"context": documents, "question": question})
            run_id = cb.traced_runs[0].id
            print(f"Run ID: {run_id}")

        return {
            "keys": {
                "documents": documents,
                "question": question,
                "generation": generation,
            }
        }
```

But I get an index out of range error:
```
    run_id = cb.traced_runs[0].id
             ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Using the `@traceable` call back I was able to hardcode some conversation_id into the metadata but then I would have to deal with getting that configured properly with unique IDs passed in and was just hoping I might be missing something with this callback.

Thanks!

**Comment by hinthornw** [comment]
Ah this is a limitation of the run collector, as it only persists the root run. I just landed a [PR](https://github.com/langchain-ai/langchain/pull/18990) to be included in the next Core release that will let you manually specify the run_id ahead of tim:
```
rag_chain.invoke({"context": documents, "question": question}, {"run_id": my_id})
```

Which would let you get around it without having to do any subclassing. The alternative right now would be to make your own  tracer that collects the ID eagerly:


```
from langchain_core.tracers import BaseTracer
from langchain_core.tracers.schemas import Run

class MyTracer(BaseTracer):
    def __init__(self):
        self.chain_runs = []
    def_persist_run(self, run: Run) -> None:
        """Persist a root run."""
        pass
   
   def _on_chain_start(self, run: Run) -> None:
        # Called on every chain start event
        self.chain_runs.append(run)
```

and then in your code

```
tracer = MyTracer()
generation = rag_chain.invoke({"context": documents, "question": question}, {"callbacks": [tracer]})
tracer.chain_runs[0].id
```

**Comment by chip-davis** [comment]
> Ah this is a limitation of the run collector, as it only persists the root run. I just landed a [PR](https://github.com/langchain-ai/langchain/pull/18990) to be included in the next Core release that will let you manually specify the run_id ahead of tim:
> 
> ```
> 
> rag_chain.invoke({"context": documents, "question": question}, {"run_id": my_id})
> 
> ```
> 
> 
> 
> Which would let you get around it without having to do any subclassing. The alternative right now would be to make your own  tracer that collects the ID eagerly:
> 
> 
> 
> 
> 
> ```
> 
> from langchain_core.tracers import BaseTracer
> 
> from langchain_core.tracers.schemas import Run
> 
> 
> 
> class MyTracer(BaseTracer):
> 
>     def __init__(self):
> 
>         self.chain_runs = []
> 
>     def_persist_run(self, run: Run) -> None:
> 
>         """Persist a root run."""
> 
>         pass
> 
>    
> 
>    def _on_chain_start(self, run: Run) -> None:
> 
>         # Called on every chain start event
> 
>         self.chain_runs.append(run)
> 
> ```
> 
> 
> 
> and then in your code
> 
> 
> 
> ```
> 
> tracer = MyTracer()
> 
> generation = rag_chain.invoke({"context": documents, "question": question}, {"callbacks": [tracer]})
> 
> tracer.chain_runs[0].id
> 
> ```
> 
> 
> 
> 

Hey, thanks for responding! That's perfect, I'll implement that workaround for now and will look out for the next release. Thanks a ton!

**Comment by chip-davis** [comment]
@hinthornw I tried to implement your solution but got this error:
```
[2024-03-19 10:55:13,246: WARNING/MainProcess] Error in MyTracer.on_llm_end callback: AttributeError("'MyTracer' object has no attribute 'run_map'")
[2024-03-19 10:55:13,247: WARNING/MainProcess] Error in MyTracer.on_chain_start callback: AttributeError("'MyTracer' object has no attribute 'run_map'")
[2024-03-19 10:55:13,248: WARNING/MainProcess] Error in MyTracer.on_chain_end callback: AttributeError("'MyTracer' object has no attribute 'run_map'")
[2024-03-19 10:55:13,249: WARNING/MainProcess] Error in MyTracer.on_chain_end callback: AttributeError("'MyTracer' object has no attribute 'run_map'")
2024-03-19 10:55:13.251 | ERROR    | app:generate:119 - Error: list index out of range
```

Any help would be appreciated!

**Comment by hinthornw** [comment]
Oh seems like you're using an older version. This should fix it up:

```
class MyTracer(BaseTracer):

    def __init__(self):
        self.run_map = {}
        self.chain_runs = []

    def_persist_run(self, run: Run) -> None:

        """Persist a root run."""

        pass

   

   def _on_chain_start(self, run: Run) -> None:

        # Called on every chain start event

        self.chain_runs.append(run)
```

**Comment by chip-davis** [comment]
That still gave me an error, but I was able to resolve it by calling `super().__init__()` in the `MyTracer` class. Thanks for your help, I really appreciate it!

**Comment by hinthornw** [comment]
Oops i missed that one - thanks!
