### ISSUE TITLE
Issue: Error in langsmith playground when using tool calls

### ISSUE THREAD

**Issue by lajnd** [langchain-ai/langsmith-sdk#541]
### Issue you'd like to raise.

I sometimes get this error in langsmith playground (seems to be related to when I use tools):
<img width="633" alt="Screenshot 2024-03-22 at 11 15 25" src="https://github.com/langchain-ai/langsmith-sdk/assets/15052881/f4561556-d716-48aa-887e-292507b60c6d">

I don't know exactly what prompts it, but it happens occasionally. It works when running the chain normally, its just related to the playground. Is this a known issue?

**Comment by hinthornw** [comment]
I believe @dqbd is working on a fix for this. Thank you for flagging!

**Comment by hinthornw** [comment]
@lajnd are you still running into this issue?

**Comment by hinthornw** [comment]
Feel free to re-open if you still have issues
