### ISSUE TITLE
Issue: 'View evaluator run' button not working from public view

### ISSUE THREAD

**Issue by chasemcdo** [langchain-ai/langsmith-sdk#544]
### Issue you'd like to raise.

Recently noticed that clicking 'View evaluator run' button while in a publicly shared version of a dataset test run seems to do nothing. Not sure if this is intentional behaviour and then button is meant to be hidden, but thought I'd raise the issue.

<img width="269" alt="image" src="https://github.com/langchain-ai/langsmith-sdk/assets/74692158/3706a696-e015-4403-9920-390da49716ef">

Also I'll add the Unauthorized error from the web console:
<img width="1265" alt="image" src="https://github.com/langchain-ai/langsmith-sdk/assets/74692158/da304b6d-b25d-44e4-9fd2-f35b8e287826">

### Suggestion:

Perhaps there is a reason that public links intentionally can't access this information, but it'd be great if the button correctly linked to the evaluator run!

Thanks!

**Comment by hinthornw** [comment]
Ya I think  we ought to hide those links for now! Would be helpful to see, agreed
