### ISSUE TITLE
Issue: LangSmith issue if cache: true in Langchain

### ISSUE THREAD

**Issue by zrg-team** [langchain-ai/langsmith-sdk#546]
### Issue you'd like to raise.

# Env

```
"langsmith": "0.1.14",
"@langchain/community": "^0.0.41",
"@langchain/core": "^0.1.49",
"@langchain/openai": "^0.0.23",
"langchain": "0.1.28",
"openai": "4.29.2",
```

# Precondition:
+ Setup LangSmith with Langchain in project
+ Model turn on cache: true
+ LangSmith will show many duplicate request and forever `in-progress` (also count those tokens twice)

# Images 
![image](https://github.com/langchain-ai/langsmith-sdk/assets/38390571/15a97fa5-6cd9-4211-848a-ad6765df39f2)
![image](https://github.com/langchain-ai/langsmith-sdk/assets/38390571/919989c5-dffe-44d8-93f7-384a072759d9)

### Suggestion:

+ Only 1 request logged
+ Token count correctly
+ No more forever in-progress process

**Comment by hinthornw** [comment]
Could you share code of a minimal example to help us reproduce? What environment are you running this in (seems like `node` server? Not edge functions?)

**Comment by hinthornw** [comment]
Marking as stale. Feel free to re-open if it's persisting!
