### ISSUE TITLE
Issue: Evaluation runs ignore child traces

### ISSUE THREAD

**Issue by jennmueng** [langchain-ai/langsmith-sdk#548]
### Issue you'd like to raise.

We're running evaluations on a pipeline that we've already instrumented with `@traceable`, when those evaluations run the trace shows up fine in the normal project view:
https://smith.langchain.com/public/1480ce7d-103e-426c-b416-cef4b9c670ac/r

However, in the evaluation run's trace it's empty:
https://smith.langchain.com/public/37a27aba-ea90-4184-9686-01e302b4de6f/r

### Suggestion:

Have the fully instrumented pipeline we have show up in the evaluation run so it's easier to review + show token count

**Comment by hinthornw** [comment]
Ah yes the handoff back to langsmith from langchain code still is manual, and the evaluation runner currently is instrumented using langchain code -  I have a ticket to fix this. Does the following work for now?


```
from langsmith.run_helpers import as_runnable

@traceable
def my_pipeline(....):
     return ....

def predict_result(inputs: dict):
    return as_runnable(my_pipeline).invoke(inputs)


run_on_dataset(llm_or_chain_factory=predict_result, ...)
```

**Comment by jennmueng** [comment]
@hinthornw nope, getting a `wrap_traceable` item with no children:
![Screenshot 2024-03-26 at 1 34 15 PM](https://github.com/langchain-ai/langsmith-sdk/assets/30991498/310fc7f0-0a77-4766-94fe-5b9c1964f36b)

**Comment by peterjrichens** [comment]
I'm running into a similar issue when running the official `Evaluation Quick Start` example. I can [see](https://smith.langchain.com/public/3c64ddcd-c8bf-4d2e-b212-6466ef2e5638/r/d9264fb6-a065-4fc8-952a-a0a2200660c4) the llm child_run in the json, but its not visualised. Is this the same bug or different?

**Comment by eltonio450** [comment]
same here, 10 ish runs in a trace, but only two displayed

**Comment by hinthornw** [comment]
Closing as stale
