### ISSUE TITLE
Trouble Retrieving All Runs from Langsmith API: Receiving 405 Error Response

### ISSUE THREAD

**Issue by NeethithevanR** [langchain-ai/langsmith-sdk#553]
### Issue with current documentation:

I am trying to retrieve all runs from Langsmith through the API, and I have also attempted using the Langsmith client. However, I am receiving a 405 error as a response.

**Comment by NeethithevanR** [comment]
@hinthornw, I'm using the public endpoint (https://api.smith.langchain.com/). Please check the code snippet below.
`
from langsmith import Client
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_API_KEY"] = "<key>"
client = Client()
runs = client.list_runs(project_name="default")
`

**Comment by hinthornw** [comment]
How frequent are you running into this? Is it on every call? (i'm having a hard time reproducing)
