### ISSUE TITLE
Issue: langsmith don't work and can't trace any data

### ISSUE THREAD

**Issue by RengarLee** [langchain-ai/langsmith-sdk#568]
### Issue you'd like to raise.

Write py according to the docs, but langsmith doesn't have the data。
Please help to explain the reason。

Refer to the documentation: https://docs.smith.langchain.com/tracing/quick_start

Below is a screenshot

![image](https://github.com/langchain-ai/langsmith-sdk/assets/23287334/7a397d6d-6bfd-4f0e-84cc-244413f130f6)
![image](https://github.com/langchain-ai/langsmith-sdk/assets/23287334/078c7c9b-0d89-4a2c-8432-9b4efb3f8513)

**Comment by hinthornw** [comment]
Could you confirm that the dotenv is being loaded correctly?

**Comment by RengarLee** [comment]
I found the reason. The reason is LANGCHAIN_TRACING_V2 Always False.
Thank you.
