### ISSUE TITLE
Issue: <langsmith  report a Error"No connection adapter......">

### ISSUE THREAD

**Issue by schrodingerisnotcat** [langchain-ai/langsmith-sdk#569]
### Issue you'd like to raise.

os.environ["LANGCHAIN_TRACING_V2"]="true"
os.environ["LANGCHAIN_API_KEY"]="xxxxxxxxx" #key is valid
..........................
..........................
when I run the program，I got the errors:
Failed to get info from <https://api.smith.langchain.com>: InvalidSchema("No connection adapters were found for '<https://api.smith.langchain.com>/info'")
Failed to batch ingest runs: LangSmithError("Failed to post <https://api.smith.langchain.com>/runs/batch in LangSmith API. No connection adapters were found for '<https://api.smith.langchain.com>/runs/batch'\n")

![Uploading image.png…]()

I don't know what's the problem, who can help me,thanks!

**Comment by hinthornw** [comment]
Hello! How are you instantiating your client?

**Comment by schrodingerisnotcat** [comment]
Today, it works. I didn't change anything.
