### ISSUE TITLE
Issue: The langsmith UI is not scrollable 

### ISSUE THREAD

**Issue by galprz** [langchain-ai/langsmith-sdk#586]
### Issue you'd like to raise.

The UI of langsmith is not scrollable (see pic - the not scrollable area in red)
![image](https://github.com/langchain-ai/langsmith-sdk/assets/7335331/36034354-e5a8-4c83-b1c0-13b39a12010f)

**Comment by hinthornw** [comment]
Reported! A fix is in flight

**Comment by hinthornw** [comment]
Should be fixed now FYI!
