### ISSUE TITLE
Issue: UUID dict key breaks tracing

### ISSUE THREAD

**Issue by fekstr** [langchain-ai/langsmith-sdk#587]
### Issue you'd like to raise.

I'm trying to use the traceable decorator on a method that returns a dict with UUID-valued keys. This seems to break tracing (sometimes the output for this step is just never logged to LangSmith and sometimes nothing that comes after it is logged either). No exception is raised. When I replace the UUID with a string, the same call works without any issues.

```py
# works
@traceable(name="name")
def func(self, input: list[UUID]) -> dict[str, str]:

# does not work
@traceable(name="name")
def func(self, input: list[UUID]) -> dict[UUID, str]:
```

### Suggestion:

Support arbitrary serializable keys

**Comment by hinthornw** [comment]
@fekstr what version are you on? 

This works for me with no problem...

https://smith.langchain.com/public/20b3d9f7-492a-47d7-87f8-b5e3b2409eea/r

```
import uuid
from langsmith import traceable

@traceable
def foo(inputs: list[uuid.UUID]) -> dict[uuid.UUID, str]:
    return {uuid.uuid4() : inputs}


foo([uuid.uuid4() for _ in range(5)])

```

**Comment by fekstr** [comment]
@hinthornw you're right, it indeed works on the latest version. Was on an earlier version. Thanks!
