### ISSUE TITLE
Add cost calculation for gpt-4-turbo

### ISSUE THREAD

**Issue by mcantrell** [langchain-ai/langsmith-sdk#597]
### Feature request

The cost is not populated when using gpt-4-turbo. The current pricing for gpt-4-turbo is

`$10.00 / 1M tokens`

### Motivation

The addition of the costs for gpt-4 provides excellent value. With gpt-4-turbo's lower cost and larger context window, it's very attractive to switch.

**Comment by hinthornw** [comment]
Thanks for flagging

**Comment by dqbd** [comment]
Should be resolved!
