### ISSUE TITLE
JS SDK traceable is not compatible with langchain JS chain.invoke tracing

### ISSUE THREAD

**Issue by mattiaseyram** [langchain-ai/langsmith-sdk#598]
### Feature request

Any chains invoked inside a function wrapped with `traceable` have separate trace ids (or vice versa, with chains calling `traceable` functions internally).

Ideally the trace id gets propagated automatically.

Related to https://github.com/langchain-ai/langchainjs/issues/5083

### Motivation

Increase compatibility with Langchain JS native tracing.

### Example

<img width="759" alt="image" src="https://github.com/langchain-ai/langsmith-sdk/assets/12214004/cf9f2348-37a0-4a0f-887e-7cd4a39e405a">

```ts
import { traceable } from 'langsmith/traceable';
import { RunnableLambda } from '@langchain/core/runnables';

const exampleRunnable = RunnableLambda.from(async (foo: string) =>
  foo.toUpperCase(),
);

exampleRunnable.name = 'exampleRunnable';

const exampleTraceable = traceable(
  async (foo: string) => {
    const result = await exampleRunnable.invoke(foo);

    console.log(result);

    return result;
  },
  {
    name: 'exampleTraceable',
  },
);

exampleTraceable('bar');
```

**Comment by hinthornw** [comment]
Ya we haven't created an automatic handoff yet. Thanks for flagging.

The way around it is to conver tthe run tree into a callback manager

**Comment by mattiaseyram** [comment]
Awesome, thanks for the reply. What's the best way to convert the RunTree into a callback manager? I'm mid implementation atm.

**Comment by hinthornw** [comment]
I'm checking with the team, but we do something similar here: https://github.com/langchain-ai/langchainjs/blob/b9f63251fc7d6b2ab5b20189bc5dca2150413b49/langchain/src/smith/runner_utils.ts#L223

We do an auto-handoff in python but I don't believe we have addedit yet in js

**Comment by mattiaseyram** [comment]
Thanks, ended up using a class similar to RunnableLambda to meet my needs as seen here https://github.com/langchain-ai/langchainjs/issues/5083

**Comment by loui7** [comment]
Same issue with RunTree's, using chain.invoke inside creates a new trace
