### ISSUE TITLE
Issue: traces not aggregated under a run when tracing an async generator

### ISSUE THREAD

**Issue by ericfeunekes** [langchain-ai/langsmith-sdk#607]
### Issue you'd like to raise.

`traceable` decorator does not correlate run ids when used on an async generator.

For example:
```python
@traceable(run_type="chain", name="expand_and_answer_questions")
async def answer(
    query: str,
) -> AsyncGenerator[ScoredDocument | Completion, None]:
    """
    Answers a given query by expanding the terms, generating expanded questions,
    mapping the questions to research, and summarizing the answers.

    Args:
        query (str): The query to be answered.

    """
    expanded_terms = expand_terms(query=query)
    documents = await call_search_function(
        query=expanded_terms,
    )
    if len(documents) == 0:
        raise RuntimeError("No answers found.")
    reranked_documents = await rerank_documents(
        query=query,
        documents=documents,
    )
    for document in reranked_documents:
         yield document

    document_context = create_document_context(
        documents=reranked_documents,
    )

    final_answer = summarize_answers(
        query=query, document_context=document_context, llm=advanced_llm
    )
    async for chunk in final_answer:
        yield Completion(content=chunk)
```

Where each child function is decorated with `traceable`, that function will generate multiple runs, where each child function has its own run_id.

If you comment out the yield statement and just return a list of completions at the end (i.e. make it not a generator). Then it works as expected with a single run_id.

### Suggestion:

It could be due to the fact that `_PARENT_RUN_TREE.set(context_run)` is happing on line 636 in `run_helpers.py` but the wrapped function is called immediately before this (line 635)

Here’s what could be happening:

1. **Initial Call Setup**: When `func` is initially called to set up the async generator (but not yet executed to yield items), the current state of context variables is captured.
   
2. **Context Variable Delay**: If `_PARENT_RUN_TREE` is set after this initial setup, any yields within the async generator won't see this updated context because they captured the context at the point of generator setup.

3. **Async Delay**: Since async functions may yield control to the event loop, other operations may intervene between the setup of the async generator and its actual execution, thereby affecting when and how context variables are updated or accessed.

So I think setting the context variables immediately before the function is called should do it? As long as intermediate results from other wrapped functions can't change the context variables in an already called function.

**Comment by hinthornw** [comment]
Thanks for flagging - will look into this

**Comment by hinthornw** [comment]
BTW an explicit way around this is to accept the run_tree in your async function an dpass that through:


```
@traceable(run_type="chain", name="expand_and_answer_questions")
async def answer(
    query: str, run_tree
) -> AsyncGenerator[ScoredDocument | Completion, None]:
    """
    Answers a given query by expanding the terms, generating expanded questions,
    mapping the questions to research, and summarizing the answers.

    Args:
        query (str): The query to be answered.

    """
    expanded_terms = expand_terms(query=query, langsmith_extra={"parent": run_tree})
    documents = await call_search_function(
        query=expanded_terms,
       langsmith_extra={"parent": run_tree},
    )
    if len(documents) == 0:
        raise RuntimeError("No answers found.")
    reranked_documents = await rerank_documents(
        query=query,
        documents=documents,
        langsmith_extra={"parent": run_tree}
    )
    for document in reranked_documents:
         yield document

    document_context = create_document_context(
        documents=reranked_documents,
        langsmith_extra={"parent": run_tree}
    )

    final_answer = summarize_answers(
        query=query, document_context=document_context, llm=advanced_llm, langsmith_extra={"parent": run_tree}
    )
    async for chunk in final_answer:
        yield Completion(content=chunk)
```

**Comment by hinthornw** [comment]
Should be fixed in 0.1.49. Let me know if it still persists.

**Comment by Heidi0039** [comment]
I have a similar problem using ThreadPoolExecutors.

When running a traceable function with a ThreadPoolExecutor from within another traceable function, the sub-calls are not correctly aggregated under the initial trace stack.

`
@traceable
def outer_func():
    with ThreadPoolExecutor() as executor:
        r = list(executor.map(inner_func, [1, 2]))

@traceable
def inner_func(x):
    print(x)
`

**Comment by hinthornw** [comment]
As mentioned above, you can explicitly pass the run_tree through as the parent. We also now have the ContextThreadPoolExecutor you can use which handles this for you.

```python
from concurrent.futures import ThreadPoolExecutor

import langsmith as ls


@ls.traceable
def my_child(val):
    return val + 1


@ls.traceable
def naive_nonnested(card):
    with ThreadPoolExecutor() as executor:
        return list(executor.map(my_child, range(card)))


@ls.traceable
def option_1(card):
    parent = ls.get_current_run_tree()
    # Explicitly pass in parent
    with ThreadPoolExecutor() as executor:
        return list(
            executor.map(
                lambda x: my_child(x, langsmith_extra={"parent": parent}), range(card)
            )
        )


@ls.traceable
def option_2(card):
    # Use LangSmith's ContextThreadPoolExecutor to propagate the context to the child threads
    with ls.ContextThreadPoolExecutor() as executor:
        return list(executor.map(my_child, range(card)))


naive_nonnested(10)  # All the children will be treated as root traces
# Both the following work
option_1(10)
option_2(10)
```
