### ISSUE TITLE
Issue: Playground does not work with images as inputs

### ISSUE THREAD

**Issue by Xargonus** [langchain-ai/langsmith-sdk#610]
### Issue you'd like to raise.

Playground does not work with base64 encoded images. When I press start, I get the following error with OpenAI's gpt-4-turbo multimodal model:
```
400 Invalid image.

Error: 400 Invalid image.
    at (vc/edge/function:407:6509)
    at (vc/edge/function:410:8909)
    at (vc/edge/function:410:9963)
    at (vc/edge/function:998:10896)
    at (vc/edge/function:125:13571)
```
With Anthropic's claude, I get the following error:
```
Anthropic only supports base64-encoded images currently.

Example: data:image/png;base64,/9j/4AAQSk...

Error: Anthropic only supports base64-encoded images currently.

Example: data:image/png;base64,/9j/4AAQSk...
    at (vc/edge/function:1501:8393)
    at (vc/edge/function:1503:4006)
    at (vc/edge/function:1503:3911)
    at (vc/edge/function:1503:3559)
    at (vc/edge/function:1503:2684)
    at (vc/edge/function:438:14958)
```

**Comment by pandaupc** [comment]
I meet the same error

**Comment by aa-morgan** [comment]
@hinthornw has this been fixed? I'm still getting the same error in the Playground for a prompt containing a single image (base64-encoded) and a small amount small.

Provider: Azure OpenAI
Model: GPT-4o (2024-08-06)
API Version: 2024-02-01
Prompt type: Chat
Prompt template: f-string
Tools: None

Error message
BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 128000 tokens. However, your messages resulted in 465133 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

**Comment by ammarraj** [comment]
@hinthornw I'm facing the same issue with Anthropic, 
```
Anthropic only supports base64-encoded images currently.

Example: data:image/png;base64,/9j/4AAQSk...
```

This is how the message image content look like, and I made sure that the `imageB64` is valid. I checked the code and I saw that this regex is being applied `/^data:(image\/.+);base64,(.+)$/` but it looks like there's something more that is causing the issue. 

```
{
      type: "image_url",
      image_url: {
        url: imageB64,
        detail: "low",
      },
    }
```

**Comment by ammarraj** [comment]
> [@hinthornw](https://github.com/hinthornw) I'm facing the same issue with Anthropic,
> 
> ```
> Anthropic only supports base64-encoded images currently.
> 
> Example: data:image/png;base64,/9j/4AAQSk...
> ```
> 
> This is how the message image content look like, and I made sure that the `imageB64` is valid. I checked the code and I saw that this regex is being applied `/^data:(image\/.+);base64,(.+)$/` but it looks like there's something more that is causing the issue.
> 
> ```
> {
>       type: "image_url",
>       image_url: {
>         url: imageB64,
>         detail: "low",
>       },
>     }
> ```

I was wrong, I'm persisting the conversation so one of the historical messages had an incompatible image so it seems like it affects the context and therefor any new messages.
