### ISSUE TITLE
Issue: LLM data fale to get to Langsmith

### ISSUE THREAD

**Issue by bilykigor** [langchain-ai/langsmith-sdk#611]
### Issue you'd like to raise.

I have LLM agent run as aws lambda with tracing via Langsmith. 
After lambda finished processing the request and returned a response, I still see run in Langsmith at status 'still running'. And finally, I see a failed run on the dashboard and seems the LLM response did not get to the Langsmith.

**Comment by bilykigor** [comment]
If I added delay 5 seconds, before lambda return, data was successfully completed to Langsmith.

**Comment by hinthornw** [comment]
Is this in python or JS?

**Comment by bilykigor** [comment]
Python

**Comment by hinthornw** [comment]
If your server's process exits before the logs are sent to langsmith, we don't have a way of capturing it right now

**Comment by refeed** [comment]
It turns out, it's already there, https://docs.smith.langchain.com/observability/how_to_guides/tracing/trace_with_langchain#ensure-all-traces-are-submitted-before-exiting
