### ISSUE TITLE
Issue: HTTPSConnectionPool(host='api.smith.langchain.com', port=443): Read timed out. (read timeout=30.0) issues using the LangSmith client

### ISSUE THREAD

**Issue by daniel-glez-ntsprint** [langchain-ai/langsmith-sdk#619]
### Issue you'd like to raise.

I have my API hosted in Azure and it randomly but very often has this error with timeouts every time I use the client for something, in this case trying to create feedback, but the same thing happens when I try to invoke client.read_run () or other functionalities. This only happens to me from the remote deployment using the Azure App Service, from the local one I never have these problems.

```
def submit_feedback(user_feedback: dict, run_id):

    try:
        result = client.create_feedback(
            run_id=run_id,
            key=user_feedback.get("type"),
            score=user_feedback.get("score"),
            value=user_feedback.get("value"),
            comment=user_feedback.get("comment"),
        )
        return result
    except Exception as e:
        raise Exception(f"Error submitting feedback: {e}")
```

Python 3.11
Langchain 0.1.16
LangSmith 0.1.47

**Comment by hinthornw** [comment]
Hi @daniel-glez-ntsprint - we increased the read timeout in 0.1.49 - could you update your langsmith version and see if it still occurs?
