### ISSUE TITLE
Cost tracking not working for ChatAnthropic()

### ISSUE THREAD

**Issue by eduardutxu** [langchain-ai/langsmith-sdk#622]
### Feature request

Cost tracking not working for ChatAnthropic(). I think it's because no 'INVOCATION_PARAMS' are shown in LangSmith.
See the comparison between info for ChatAnthropic() and ChatOpenAI():

![ChatAnthropic](https://github.com/langchain-ai/langsmith-sdk/assets/53401578/e38d480e-0360-44a9-9bad-81a44cb21535)
![ChatOpenAI](https://github.com/langchain-ai/langsmith-sdk/assets/53401578/24a72e9c-4ce5-43d8-b86b-102ed7c86927)

### Motivation

The Anthropic ones are some of the best quality language models currently available. It's very important to have cost tracking working for it on the LangSmith platform.

**Comment by eduardutxu** [comment]
No, it's in Python, not JS. The screenshots are from LangSmith.

**Comment by deskobar** [comment]
I'm looking for this feature, but I cannot find it. Any workaround available?

**Comment by eduardutxu** [comment]
What do you mean deskobar? This feature is in LangSmith: when you look at an LLM cal within a Trace, you'll see the Metadata section. BTW, this issue got resolved; now cost tracking for ChatAnthropic works well in LangSmith :-)

**Comment by deskobar** [comment]
> What do you mean deskobar? This feature is in LangSmith: when you look at an LLM cal within a Trace, you'll see the Metadata section. BTW, this issue got resolved; now cost tracking for ChatAnthropic works well in LangSmith :-)

Oh, could you please help me?

This is my code.

<img width="625" alt="image" src="https://github.com/langchain-ai/langsmith-sdk/assets/53846644/42e61ca3-0e96-4541-978c-664bd9945be4">

I have installed 

```pyproject
langchain-anthropic = "^0.1.17"
langchain-core = "^0.2.11"
```

On smith.langchain.com I see after each request

<img width="1138" alt="image" src="https://github.com/langchain-ai/langsmith-sdk/assets/53846644/f18fdc2a-8987-42ae-a07c-d3a107c09b6f">

So, what am I doing wrong?

**Comment by eduardutxu** [comment]
Hi deskobar, I think this is not the place for 'help' with your code. Try discord, please. Thanks.
