### ISSUE TITLE
Issue: [LangSmith Website] memory leak on firefox

### ISSUE THREAD

**Issue by ldorigo** [langchain-ai/langsmith-sdk#624]
### Issue you'd like to raise.

![image](https://github.com/langchain-ai/langsmith-sdk/assets/8631181/d3c8244f-61f0-433b-9000-e49dbfd91bca)

Langsmith is always quite heavy, but sometimes the memory consumption goes way overboard and crashes my browser/entire laptop - see screenshot.

This isn't a new issue, just didn't report before.

**Comment by hinthornw** [comment]
Thanks for raising! This is when viewing the website? Or when running tracing in the browser?

**Comment by ldorigo** [comment]
When tracing. Seems to be mainly after it's left open in the background.

**Comment by hinthornw** [comment]
Got it - do you have any example code snippet of something you're tracing? is this with the traceable HOF in js?

**Comment by jacoblee93** [comment]
@ldorigo just to be clear - you're running LLM calls/code in the browser and putting your LangSmith key there? Your screenshot above makes it look like you're viewing https://langchain.com.

**Comment by ldorigo** [comment]
Sorry, I misunderstood - it's while *looking at traces* in the langsmith web app that this happens. Wasn't aware you could run tracing in-browser so I assumed this is what you meant by "running tracing".
