### ISSUE TITLE
DOC: How to setup LangSmith threads in LangServe

### ISSUE THREAD

**Issue by camba1** [langchain-ai/langsmith-sdk#625]
### Issue with current documentation:

The documentation indicates how to setup thread in LangChain using the SDK  (https://docs.smith.langchain.com/monitoring/faq/threads)

```python
from langchain_anthropic import ChatAnthropic
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.output_parsers import StrOutputParser
import uuid
model = ChatAnthropic(model="claude-3-haiku-20240307")
prompt = ChatPromptTemplate.from_messages([('placeholder', "{messages}")])
chain = prompt | model
messages = [HumanMessage(content="hi! I'm bob")]
config = {"metadata": {"conversation_id": str(uuid.uuid4())}}
response = chain.invoke({"messages": messages}, config=config)
messages = messages + [response, HumanMessage(content="whats my name")]
response = chain.invoke({"messages": messages}, config=config)
```
But how do you accomplish the same thing if the application is running in LangServe? My understanding is that you pass the chain to LangServe and it is LangServe that runs it when a request comes in. So, where would you add the thread configuration?

### Idea or request for content:

Add another tab to the section where it explains how to set this up in python and LangChain Python with an example on how to accomplish this on LangServe.

**Comment by hinthornw** [comment]
Hi @camba1 - are you using `RemoteRunnable`? If so, you can pass in metadata the same way as you would here!

**Comment by nrakocz** [comment]
This does not work for me

**Comment by ashantanu** [comment]
facing the same issue. using `metadata` or `configurable` config does not work
