### ISSUE TITLE
langsmith.client:Failed to batch ingest runs: LangSmithError('Failed to POST') 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by Waelaburezeq** [langchain-ai/langsmith-sdk#637]
### Issue you'd like to raise.

Using google colab, and following the LangServe documentation with a simple LLM call after setting up my LangServe API Key, I am getting this error:

Reference:[https://docs.smith.langchain.com/tracing/quick_start]

> WARNING:langsmith.client:Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError('403 Client Error: Forbidden for url: [https://api.smith.langchain.com/runs/batch](https://api.smith.langchain.com/runs/batch/)', '{"detail":"Forbidden"}')')

Here is my code:

```
%env LANGCHAIN_TRACING_V2=True
%env LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
%env LANGCHAIN_API_KEY=userdata.get('langsmith_api_key')

from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI()
llm.invoke("Hello, world!")
```
The LLM call is succesfull, but the LangSmith package is not working! Tried disconnecting the run time with no luck

**Comment by hinthornw** [comment]
If you run `print(os.environ["LANGCHAIN_API_KEY"])` what does it show

**Comment by Waelaburezeq** [comment]
hi, 

it gives 

userdata.get('langsmith_api_key')#'ls__88.........'

where Is__88..... is my LangChain key

**Comment by hinthornw** [comment]
`%env LANGCHAIN_API_KEY=userdata.get('langsmith_api_key'`  is a shell command, so you're setting hte API key to the litral string "userdata.get('langsmith_api_key')#'ls__88.........'" rather than just the API key. Just set it directly or use `os.environ["LANGCHAIN_API_KEY"] = userdata.get('langsmith_api_key')`

**Comment by Waelaburezeq** [comment]
I tried, same error. Here is the updated version *(knowing that it is
working in local VS, but not in google colab)*

os.environ['LANGSMITH_API_KEY'] = 'ls__88.......'
os.environ['LANGCHAIN_TRACING_V2'] ="true"
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_PROJECT = 'pt-earnest-implement-95'


Error:

WARNING:langsmith.client:Failed to batch ingest runs:
LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch
in LangSmith API. HTTPError(\'403 Client Error: Forbidden for url:
https://api.smith.langchain.com/runs/batch\
<https://api.smith.langchain.com/runs/batch/>',
\'{"detail":"Forbidden"}\')')

**Comment by ashwath007** [comment]
**I have tried too, but getting the same error -** 

Exception: Page.evaluate: Connection closed while reading from the driver
WARNING:langsmith.client:Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'403 Client Error: Forbidden for url: [https://api.smith.langchain.com/runs/batch\](https://api.smith.langchain.com/runs/batch/)', \'{"detail":"Forbidden"}\')')

**Comment by RobertCorwin-AustinAI** [comment]
Similar error here - Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'422 Client Error: unknown for url: https://api.smith.langchain.com/runs/batch\', \'{"detail":"start_time must be an ISO 8601 timestamp"}\')')

LangChain 0.2.6
LandSmith 0.1.82

any ideas?

**Comment by apisani1** [comment]
I have the same issue:

Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'403 Client Error: Forbidden for URL: https://api.smith.langchain.com/runs/batch\', \'{"detail":"Forbidden"}\')')

I wrote a test notebook in Jupiter and I have no issue.

The Python script and the Jupiter notebook use the same conda environment and the same environment variable values including the Langchain API.

**Comment by kordou** [comment]
Same here. used to work , now it does not. all env variables correct

**Comment by yunatseng** [comment]
I had the same problem today. I checked my .env file and commented out "LANGCHAIN_ENDPOINT=https://api.smith.langchain.com".
After that, the error went away. it worked for me.

**Comment by RobertCorwin-AustinAI** [comment]
> I had the same problem today. I checked my .env file and commented out "LANGCHAIN_ENDPOINT=https://api.smith.langchain.com". After that, the error went away. it worked for me.

hmmm, thanks for posting but that did not work for me.  I still get the following error, although I'd note that it still knows the endpoint despite me commenting it out.  Do you have any other env vars or other settings related to the endpoint in your code?  thanks.

Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'422 Client Error: unknown for url: https://api.smith.langchain.com/runs/batch\', \'{"detail":"start_time must be an ISO 8601 timestamp"}\')')

**Comment by RobertCorwin-AustinAI** [comment]
OK here is a bit more info.  I paused the code at the error on line 123 of langsmih\utils.py  and investigated the request it was trying to make.  the start_time in that HTTP request was:

2024-07-09T17:24:19.186968+00:00

and this is seemingly what it is complaining about.  I'm not a date expert but I think this date has too many decimal places for ISO 8601.  I don't have time to find where that date is being made but perhaps someone at Langchain can take a look?

**Comment by apisani1** [comment]
In my case, I found a call to langchain that was being done before the loading of my dotenv file. The issue was solved by moving the loading of the dotenv file to the first module being initialized.

**Comment by andrea-fater** [comment]
Hi everyone.

Same issue here. I followed these steps:

- Created a new fresh environment:
`conda create --name test_langsmith python=3.11`
`conda activate test_langsmith`
`pip install -U langchain langchain-openai`
`pip install python-dotenv`

- Created and .env file with the following content:
```
LANGCHAIN_TRACING_V2="true"
LANGCHAIN_ENDPOINT="https://eu.smith.langchain.com/"
LANGCHAIN_API_KEY="my_lansmith_key"
LANGCHAIN_PROJECT="Test_project"

OPENAI_API_KEY="my_openai_key"
```

- Created a "main.py" script with the following content:

```
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
load_dotenv(".env")

if __name__ == "__main__":

    llm = ChatOpenAI()
    llm.invoke("Hello, world!")

```

- I run the script and I get the following error:
```
Failed to get info from https://eu.smith.langchain.com: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Failed to batch ingest runs: LangSmithError("Failed to POST https://eu.smith.langchain.com/runs/batch in LangSmith API. HTTPError('405 Client Error: Method Not Allowed for url: https://eu.smith.langchain.com/runs/batch', '<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n')")
Failed to batch ingest runs: LangSmithError("Failed to POST https://eu.smith.langchain.com/runs/batch in LangSmith API. HTTPError('405 Client Error: Method Not Allowed for url: https://eu.smith.langchain.com/runs/batch', '<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n')")
```

Any help please!

**Comment by apisani1** [comment]
> Hi everyone.
> 
> Same issue here. I followed these steps:
> 
> * Created a new fresh environment:
>   `conda create --name test_langsmith python=3.11`
>   `conda activate test_langsmith`
>   `pip install -U langchain langchain-openai`
>   `pip install python-dotenv`
> * Created and .env file with the following content:
> 
> ```
> LANGCHAIN_TRACING_V2="true"
> LANGCHAIN_ENDPOINT="https://eu.smith.langchain.com/"
> LANGCHAIN_API_KEY="my_lansmith_key"
> LANGCHAIN_PROJECT="Test_project"
> 
> OPENAI_API_KEY="my_openai_key"
> ```
> 
>  * Created a "main.py" script with the following content:
> 
> ```
> from langchain_openai import ChatOpenAI
> from dotenv import load_dotenv
> load_dotenv(".env")
> 
> if __name__ == "__main__":
> 
>     llm = ChatOpenAI()
>     llm.invoke("Hello, world!")
> ```
> 
>  * I run the script and I get the following error:
> 
> ```
> Failed to get info from https://eu.smith.langchain.com: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
> Failed to batch ingest runs: LangSmithError("Failed to POST https://eu.smith.langchain.com/runs/batch in LangSmith API. HTTPError('405 Client Error: Method Not Allowed for url: https://eu.smith.langchain.com/runs/batch', '<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n')")
> Failed to batch ingest runs: LangSmithError("Failed to POST https://eu.smith.langchain.com/runs/batch in LangSmith API. HTTPError('405 Client Error: Method Not Allowed for url: https://eu.smith.langchain.com/runs/batch', '<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n')")
> ```
> 
> Any help please!

Try loading the .env file before importing any langchain module.

**Comment by andrea-fater** [comment]
I have found the solution.

The correct LANGCHAIN_ENDPOINT environment variable is "https://eu.api.smith.langchain.com/".

The langsmith platform, instead, tells you to use the value "https://eu.smith.langchain.com/":
![image](https://github.com/user-attachments/assets/cfd95edc-208f-4d57-8699-7ccac5bb7ad4)

**Comment by RobertCorwin-AustinAI** [comment]
Thanks @andrea-fater and @apisani1 for posting your solutions, however neither apply to my setup and I believe as mentioned here that there is an underlying problem with one of the upstream date formats which is actually causing a real bug to happen.  This is preventing us from upgrading langchain and affecting our willingness to purchase a paid plan.  If someone at Langchain could kindly take a look that'd be greatly appreciated

**Comment by MCSJ1** [comment]
I also am getting the same issue, have only tried in VS code.

**Comment by gunardilin** [comment]
I have got the same issue. Has someone found a solution?

**Comment by alibabadoufu** [comment]
Same issue here. I think for large inputs or outputs its not able to send to langsmith thus causing the error. We might need to use client to mask the inputs and outputs if they are too large?

**Comment by RobertCorwin-AustinAI** [comment]
I still think there is a formatting error in the dates, I traced through their code and it tries to submit an improperly formatted date to their own REST API causing the error

This issue is still preventing us from using and recommending the entire library as much as we'd like

**Comment by apisani1** [comment]
In my case, the issue was solved by ensuring that the LangChain API was set up in the environment before any import from the library.

I use a .env file, which was being loaded after importing some modules from langchain.

I hope that this helps some of you.

**Comment by brnrc** [comment]
The `environment_variables` in the config section seem to have no effect. It only worked for me after exporting those in the shell and then running litellm.

**Comment by RobertCorwin-AustinAI** [comment]
sadly, we had to turn off langchain tracing in one project but on a lark I tried it in another project.  Again we get an error!! 

Failed to batch ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError('422 Client Error: unknown for url: https://api.smith.langchain.com/runs/batch', '{"detail":"int too big to convert"}')

it seems the langsmith code which calls the tracing API needs some serious work to validate the parameters it sends!  it is not usable for us in 2 out of 2 projects, so far.  I think this is highly unlikely due to any env or config issue, this is some error whereby somehow langchain itself in Python is sending invalid values to its own REST API on the net.

**Comment by RobertCorwin-AustinAI** [comment]
Langchain staff: we will sign up as a company (Austin AI) for multiple seats once this issue is resolved....  but cannot if it is not...

**Comment by luizweb** [comment]
I was facing the same reported issue. 
Managed to solve it by creating a **NEW** Personal Access Token API for the project.

**Comment by RobertCorwin-AustinAI** [comment]
> I was facing the same reported issue. Managed to solve it by creating a **NEW** Personal Access Token API for the project.

thanks for sharing, however that did not work for us, we get the same error as before using a new PAT, see below, and once again some of the calls get logged to langsmith but others fail.

Failed to batch ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError('422 Client Error: unknown for url: https://api.smith.langchain.com/runs/batch', '{"detail":"int too big to convert"}')

**Comment by Nagidrop** [comment]
I was facing this and found out I reached the 5000 free rate limit. Check your rate limit in "Usage and Billing" section to see if you're being rate limited.

**Comment by sumitkrtiwari** [comment]
Clean your environment. In case of Google COLAB, do below steps:
1) Create a new LANGSmith key
2) Disconnect and delete the COLAB runtime. 
3) Create a new COLAB run time
4) pip install -U langchain langchain-openai
5) LANGSMITH_TRACING="true"
LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
LANGSMITH_API_KEY="<LANGSMOTH API KEY>"
LANGSMITH_PROJECT="<Project Name>"
OPENAI_API_KEY="<OPEN API KEY>"
6) import os
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
os.environ["LANGCHAIN_TRACING_V2"] = LANGSMITH_TRACING
os.environ["LANGCHAIN_PROJECT"] = LANGSMITH_PROJECT
os.environ["LANGCHAIN_API_KEY"] = LANGSMITH_API_KEY
7) Try LLM Call and tracing should work

**Comment by ChrisClaude** [comment]
For non eu endpoints you have to specify
