### ISSUE TITLE
AttributeError when trying to change the destination project at runtime using client.stream

### ISSUE THREAD

**Issue by ByPatrick** [langchain-ai/langsmith-sdk#655]
Hello,

I am trying to implement the feature to change the destination project at runtime as described in the documentation here: [Changing the destination project at runtime](https://docs.smith.langchain.com/tracing/faq/customizing_trace_attributes#changing-the-destination-project-at-runtime).

However, I encounter an issue when I use client.stream instead of the regular method described in the docs. The error I receive is:
`AttributeError: 'LangChainTracer' object has no attribute 'handlers'`

This occurs when executing the following line of code:

`callback_manager = get_callback_manager_for_config(config)`

Could you please help me understand how to resolve this issue? It seems that the 'LangChainTracer' object may not have the 'handlers' attribute when used with client.stream. Is there a different approach or additional configuration required when using client.stream?

Thank you for your assistance!

**Comment by eyurtsev** [comment]
cc @hinthornw

**Comment by hinthornw** [comment]
@ByPatrick are you by any chance doing:

```python
chain.stream(..., {"callbacks": LangChainTracer()})
```

Instead of
```python
chain.stream(..., {"callbacks": [LangChainTracer()]})
```
?

If not, could you share a minimum reproducible code example and your langchain version?

**Comment by ByPatrick** [comment]
First, I need to clarify something I didn't mention earlier: I'm using langserve.client.

Versions:
langserve: 0.0.38
langchain: 0.1.8

Below is the minimum reproducible code example:

tracer = langchain.callbacks.tracers.LangChainTracer(project_name=project_name)
config = {
    "callbacks": [tracer],
    "configurable": {"xxx": xxx}
}

chain = langserve.client.RemoteRunnable(url)
async for chunk in chain.astream(input={"prompt": prompt}, config=config):
    ...

Thank you for your response!

**Comment by ByPatrick** [comment]
> @ByPatrick are you by any chance doing:
> 
> ```python
> chain.stream(..., {"callbacks": LangChainTracer()})
> ```
> 
> Instead of
> 
> ```python
> chain.stream(..., {"callbacks": [LangChainTracer()]})
> ```
> 
> ?
> 
> If not, could you share a minimum reproducible code example and your langchain version?

You're right, I checked my code and fixed it, and now it works properly. Thank you very much!
