### ISSUE TITLE
Internal Server Error when trying to Add Evaluator

### ISSUE THREAD

**Issue by andrewmatchday** [langchain-ai/langsmith-sdk#661]
### Issue you'd like to raise.

I tried to add and save a new evaluator but I get an internal server error with no additional details on save.
`POST https://api.smith.langchain.com/runs/rules 500 (Internal Server Error)`
`{"detail":"Internal server error"}`

This happens for both inline prompt and using a prompt from the hub like `rlm/rag-document-relevance`

**Comment by hinthornw** [comment]
Should be fixed!
