### ISSUE TITLE
Issue: 401 Unauthorized when following langsmith tracing instructions

### ISSUE THREAD

**Issue by sahellebusch** [langchain-ai/langsmith-sdk#666]
### Issue you'd like to raise.

Added my first project and API keys to test out the tracing functionality. Followed the instructions in the docs and set the following values:

```
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="REDACTED"
```

And I keep getting the following:
```
Error: Failed to batch create run: 401 Unauthorized {"detail":"Invalid token"}
```

Everything else works. The model calls and responds correctly. Any advice here?

**Comment by hinthornw** [comment]
Could you confirm that if you create a new API key in the app and re-run this code it still doesn't work?

**Comment by sahellebusch** [comment]
I've already created a new API key twice now.

**Comment by hinthornw** [comment]
What is the actual code you are running?

**Comment by sahellebusch** [comment]
Omitting some details for brevity.
```ts
this.openAI = new ChatOpenAI({
      openAIApiKey: process.env.OPENAI_API_KEY,
      modelName: 'gpt-4-turbo-preview',
      temperature: 0.8,
    });

const prompt = await hub.pull<ChatPromptTemplate>(
      'seanhellebusch/customized-exercise-audio-cues',
    );

    const rep = await prompt
      .pipe(this.openAI)
      .pipe(this.outputParser)
      .invoke({ input, data: this.getDataXml() });
```

**Comment by VINHTRAN-VICIDEV** [comment]
I have the same problem and I think the cause is we haven't added the payment yet?

**Comment by hinthornw** [comment]
No payment is required to send traces to langsmith. 

@sahellebusch are you including the literal '"' quotes in your api key?

**Comment by sahellebusch** [comment]
@hinthornw - nope.

**Comment by 03balogun** [comment]
Having the same issue.

**Comment by VINHTRAN-VICIDEV** [comment]
thanks @hinthornw, it's working

**Comment by sahellebusch** [comment]
@VINHTRAN-VICIDEV - Does your issues relate to mine at all? If yes, how did you resolve?

**Comment by sahellebusch** [comment]
Welp, not sure where I copy/pasted it from but it's the "HUB" api key, needs to just be `LANGCHAIN_API_KEY` and it all works just fine.

https://github.com/langchain-ai/langsmith-sdk/blob/main/js/src/client.ts#L445
