### ISSUE TITLE
Issue: RunTree .end only works in openai format

### ISSUE THREAD

**Issue by agamm** [langchain-ai/langsmith-sdk#670]
### Issue you'd like to raise.

When I tried sending `rt.end('string')` it failed with:
> WARNING:langsmith.client:Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'422 Client Error: Unprocessable Entity for url: https://api.smith.langchain.com/runs/batch\'

If I formatted the output like so, it worked: 
```
rt.end(outputs={"choices": [{"message": {"content": response}}]})
```

### Suggestion:

Make it work with regular strings too.

**Comment by hinthornw** [comment]
That's because the end is required to be a dictionary.

**Comment by hinthornw** [comment]
It can be any dictionary. It doesn't have to be OpenAI's format

**Comment by agamm** [comment]
For me it failed.
