### ISSUE TITLE
Issue: Wrong y Axis values in the token graphs of the testing section

### ISSUE THREAD

**Issue by simon-enosis** [langchain-ai/langsmith-sdk#680]
In the **Datasets and Testing** section, for the token related graphs, the y axis values are wrong.

![image](https://github.com/langchain-ai/langsmith-sdk/assets/89076010/1a4d245c-790f-45b6-b50d-acbeed0201bc)
![image](https://github.com/langchain-ai/langsmith-sdk/assets/89076010/d4f15b6d-00de-410d-bf3d-6ab592741279)
![image](https://github.com/langchain-ai/langsmith-sdk/assets/89076010/898b363d-36aa-4e74-8f6c-d92d2bd8f05e)
![image](https://github.com/langchain-ai/langsmith-sdk/assets/89076010/7a6cf36c-0bcf-4e97-8e7d-ea5e3c690fee)

**Comment by hinthornw** [comment]
Flagged to the relevant person
