### ISSUE TITLE
Issue: BadRequestError: Invalid parameter when using 'tool_calls' with 'functions'

### ISSUE THREAD

**Issue by vikyw89** [langchain-ai/langsmith-sdk#705]
### Issue you'd like to raise.

I encountered an issue with the `langsmith` library where an error is thrown when using langgraph combined with llamaindex retrieval inside tool call.

**Error Details:**
```
Error Type: BadRequestError
Message: Error code: 400 - {'error': {'message': "Invalid parameter: 'tool_calls' cannot be used when 'functions' are present. Please use 'tools' instead of 'functions'.", 'type': 'invalid_request_error', 'param': 'messages.[2].tool_calls', 'code': None}}
```

**Comment by hinthornw** [comment]
The error in this ticket is from your model provider, and it's telling you that you're mixing function and tool calling. This is all unrelated to langsmith.

**Comment by vikyw89** [comment]
This happens when I'm using evaluate dataset function, but doesn't happen when I'm using automatic evaluation using trigger. As for my code, things happen smoothly without these error

**Comment by hinthornw** [comment]
Could you share a trace so I can try to help debug?

**Comment by Birdy647JH** [comment]
I also meet this issue, could you please share how did you fix this bug?
