### ISSUE TITLE
New `StructuredPrompt` does not work with `RunnableParallel`

### ISSUE THREAD

**Issue by dan-cooke** [langchain-ai/langsmith-sdk#710]
### Issue you'd like to raise.

Just like to report an issue i've noticed with the new StructuredPrompt created via LangSmith (really lovely UI so would love to see this fixed)

Creating a structured prompt via the UI

And then invoking it with a runnable parallel causes it to skip the structured formatting

```.py

        prompt = hub.pull("dancooke/structured_prompt")

        chain: Runnable = (
            {"input": RunnablePassthrough(), "context": retriever} | prompt | llm
        )

        chain .invoke("what is the meaning of life")

```

**Comment by hinthornw** [comment]
The LLM still can choose whether or not to use the schema provided this way unless you set the tool_choice appropriately (to require that it be used)

**Comment by dan-cooke** [comment]
@hinthornw thanks for your reply, do you have a link to any documentation about this? Haven’t been able to find any reference to this stuff in the docs

**Comment by hinthornw** [comment]
Here's a relevant doc: https://python.langchain.com/v0.2/docs/how_to/tool_choice/
