### ISSUE TITLE
Issue: Dataset Iteration in Experiment Not Properly Looping Through Examples

### ISSUE THREAD

**Issue by himansrivastava** [langchain-ai/langsmith-sdk#711]
### Issue you'd like to raise.

I encountered a problem while running an experiment with a dataset containing only three examples.

**Problem Description:**

When running the following experiment:

```
from langsmith.evaluation import evaluate

def exact_match(run: Run, example: Example):
    return {
        "key": "exact_match",
        "score": run.outputs["output"] == example.outputs["output"],
    }

experiment_results = evaluate(
    chain,
    data=DATASET_NAME,
    evaluators=[exact_match],
)
# chain here is a Crew AI agent
```

I noticed that the examples were not being properly passed to the Crew AI agent during the experiment runs. Specifically:

1. In one iteration, the same example was passed to all three runs of the agent.
2. In another iteration, the correct example was passed in two runs, but an incorrect example was passed in the third run.
3. This behaviour repeated multiple times with different combinations.

**Steps to Reproduce:**

1. Create a dataset with three examples.
2. Define the exact_match evaluation function as shown above.
3. Use a Crew AI agent as a chain
4. Run the experiment using the evaluate function.

**Expected Behavior:**

Each example in the dataset should be correctly and uniquely passed to the corresponding runs of the Crew AI agent.

**Observed Behavior:**

The examples are inconsistently passed to the agent, resulting in incorrect pairings between runs and examples.

Please investigate this issue and provide guidance on how to ensure correct example iteration during experiments.

Thank you!

**Comment by hinthornw** [comment]
is `chain` callable? what does that do?

**Comment by hinthornw** [comment]
You'd have to evaluate `CrewAgent.kickoff` directly
