### ISSUE TITLE
Langgraph ToolExecutor creates separate trace

### ISSUE THREAD

**Issue by Blubberblub** [langchain-ai/langsmith-sdk#720]
### Issue you'd like to raise.

I tested out the langgraph agent executor from the langgraph examples(see link at the end) and enabled langsmith tracing through env variable `LANGCHAIN_TRACING_V2=true`.

Looking at the trace in langsmith I noticed that one invocation of the graph actually created two traces. The first one is the one for the agent and for some reason the tool call  gets a separate trace. The reson probably is that the `ToolExecutor` itself is an instance of `RunnableCallable`. I didn't test it out with a larger graph yet but this could potentially be a general issue when using multiple runnables in a graph.

 I think this is not desired from a tracing perspective. Is there any way to fix this and "unify" the trace?

Link to example code:
https://github.com/langchain-ai/langgraph/blob/main/examples/agent_executor/base.ipynb

**Comment by hinthornw** [comment]
Are you using async and python < 3.11? 

What versions of python and LangChain and langsmith are you using?

**Comment by Blubberblub** [comment]
@hinthornw Sorry for not providing the basic info. Yes im using async running a function with asyncio.
Python 3.10.6
langchain                 0.2.0
langchain-community       0.2.0
langchain-core            0.2.1
langchain-openai          0.0.8
langgraph                 0.0.54
langserve                 0.2.0
langsmith                 0.1.47

**Comment by hinthornw** [comment]
Gotcha. If you use python 3.11 it will work. It will also work in the next version of langgraph

**Comment by Blubberblub** [comment]
@hinthornw So i switched to python3.11 and did some further tests. When im not using async i get one trace for the langgraph run and two separate ones for the two tool call executions.

![image](https://github.com/langchain-ai/langsmith-sdk/assets/9118119/43d2d336-6bcc-4a91-b733-7bdf73f00b57)

The only way to fix this i found, is to explicitly only trace the app by setting `LANGCHAIN_TRACING_V2=true` and using the langchain in callbacks like this:

```
tracer = LangChainTracer()

for s in app.stream(
    inputs,
    config={"callbacks": [tracer]}
):
    print(s)
    print("----")
```

For the async part i have to test further. I realized that i can't none async functions (e.g. `app.stream()`) on my graph if i have async functions in there. This makes kind of sense but it is a little hard to graspfrom the error message i got. I think there could be a better error for this instead of what i got:

```
Traceback (most recent call last):
  File "/home/tim/yog-sothoth/services/chat/langgraph_backend.py", line 347, in <module>
    for s in app.stream(inputs):
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 876, in stream
    _panic_or_proceed(done, inflight, step)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1422, in _panic_or_proceed
    raise exc
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.11/site-packages/langgraph/pregel/retry.py", line 66, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2393, in invoke
    input = step.invoke(
            ^^^^^^^^^^^^
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.11/site-packages/langgraph/utils.py", line 86, in invoke
    if accepts_config(self.func)
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/yog-sothoth/services/chat/venv/lib/python3.11/site-packages/langchain_core/runnables/utils.py", line 86, in accepts_config
    return signature(callable).parameters.get("config") is not None
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 3272, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 3020, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 2443, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: None is not a callable object
```

I will give more info once i made the async part work for me.

**Comment by hinthornw** [comment]
Ah this is trickier than I thought, then. I'll try to investigate. Thank you for your patience

**Comment by Blubberblub** [comment]
> Ah this is trickier than I thought, then. I'll try to investigate. Thank you for your patience - seems to be a couple action items for our side:
> 
> 1. Improve error messaging in the runnable utils
> 2. debug what is going on that breaks the trace contiguity for both sync and async streaming here

Thanks for looking into this. Are there resources on how to prepare the graph for sync and async cases? Because we use the `astream_events()` for user output (llm token streaming) and i think last time i tested the langsmith `evaluate()` was working better with the sync version.

**Comment by hinthornw** [comment]
Another good question. The `aevaluate()`  (note the "a" at the beginning) function is an async method designed for evaluating asynchronous functions - have you tried that out before?

**Comment by hinthornw** [comment]
I'm trying to reproduce this behavior but haven't yet succeeded. E.g., this works:

```
async def test_stream_runnable_callable() -> None:

    @tool
    def grandchild(x: int):
        """A grandchild function."""
        return x
    

    async def my_async_func(_, config) -> None:
        return await grandchild.ainvoke(_, config)

    def my_sync_func(_, config) -> None:
        return grandchild.invoke(_, config)

    runnable = RunnableCallable(
        my_sync_func,
        my_async_func,
        name="test",
        trace=False, # This is to make the code paths executed the same as if we were using the ToolExecutor
    )

    def prelude(_):
        return _

    sequence = (prelude | runnable).with_config(run_name="Foo")
    rc = RunCollectorCallbackHandler()
    result = list(sequence.stream({"x": 1}, {"callbacks": [rc]}))
    assert result == [1]
    assert len(rc.traced_runs) == 1
    run = rc.traced_runs[0]
    assert run.name == "Foo"
    assert run.child_runs[0].name == "prelude"
    assert run.child_runs[1].name == "grandchild"

    with collect_runs() as rc:
        results = []
        async for result in sequence.astream({"x": 1}):
            results.append(result)
        assert results == [1]
        assert len(rc.traced_runs) == 1
        run = rc.traced_runs[0]
        assert run.name == "Foo"
        assert run.child_runs[0].name == "prelude"
        assert run.child_runs[1].name == "grandchild"
 ```

**Comment by RamiAwar** [comment]
This also worked for me, thanks for posting this workaround!

Not sure if this helps @hinthornw , but I had this using a complicated LangGraph with the SQL toolkit defined in some agent tutorials. 

Your sample code might be missing langgraph, or the more manually defined tools.

**Comment by hinthornw** [comment]
If it's the ToolExecutor you're using, you can likely pass the config directly:

```python
def my_node(state, config: RunnableConfig):
    ...
    my_tool_executor.invoke(...., config)
```

**Comment by Blubberblub** [comment]
@hinthornw I don't exactly understand why this is solving the issue but it is a solution.
