### ISSUE TITLE
Failed to batch ingest runs: LangSmithError

### ISSUE THREAD

**Issue by jerichoi224** [langchain-ai/langsmith-sdk#721]
### Issue you'd like to raise.

Hi, I'm just trying out Langsmith/LangChain, and I'm was having trouble with the most basic thing..

I'm simply following the steps here: https://docs.smith.langchain.com/ on my jupyter notebook (also tried on google colab)

Ran below, since it showed for shell.
```
!export LANGCHAIN_TRACING_V2=true
!export LANGCHAIN_API_KEY='sv2_pt_....'
# The below examples use the OpenAI API, though it's not necessary in general
!export OPENAI_API_KEY='sk-proj-......'
```

Also ran this, which I found from the rag from scratch notebook
```python
import os
os.environ['LANGCHAIN_TRACING_V2'] = 'true'
os.environ['LANGCHAIN_ENDPOINT'] = 'https://api.smith.langchain.com'
os.environ['LANGCHAIN_API_KEY'] = 'sv2_pt_......'
```

Then when I run the following code
```pythong
import openai
from langsmith.wrappers import wrap_openai
from langsmith import traceable

# Auto-trace LLM calls in-context
client = wrap_openai(openai.Client())

@traceable # Auto-trace this function
def pipeline(user_input: str):
    result = client.chat.completions.create(
        messages=[{"role": "user", "content": user_input}],
        model="gpt-3.5-turbo"
    )
    return result.choices[0].message.content

pipeline("Hello, world!")
# Out:  Hello there! How can I assist you today?
```

I get the following
![Screenshot 2024-05-22 at 9 34 21 PM](https://github.com/langchain-ai/langsmith-sdk/assets/4184001/dcd3c3af-86e5-462e-bd75-e45af7cf58b5)

which says 
```
`Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'403 Client Error: Forbidden for url: [https://api.smith.langchain.com/runs/batch\',](https://api.smith.langchain.com/runs/batch/',) \'{"detail":"Forbidden"}\')')`
```

Pretty sure I followed everything properly, but not sure why I can't get langsmith to work.. was hoping I could find some help.

**Comment by hinthornw** [comment]
Have you confirmed that your API key is valid? A 403 indicates you are not authorized to post traces to langsmith.

**Comment by hinthornw** [comment]
Looking at your notebook screenshot, i think you're missing the 'l' 

```
!export LANGCHAIN_API_KEY='lsv2_pt_....'
```

instead of

```
!export LANGCHAIN_API_KEY='sv2_pt_....'
```

**Comment by jerichoi224** [comment]
Wow. I feel stupid.. can't believe I failed the basic of programming (copy paste)
Thank you so much! Didn't even think to recheck the API Key..
