### ISSUE TITLE
Multi-user support

### ISSUE THREAD

**Issue by mdimercurio** [langchain-ai/langsmith-sdk#73]
It would be great to be able to setup an organization and invite other users to Langsmith to have multiple users monitor the prod environment, share and contribute to datasets and run the same tests.

**Comment by hinthornw** [comment]
@mdimercurio We will be rolling out team support slowly starting this week. If you would like earlier access, could you send an email to support@langchain.com , please? Thank you!

**Comment by hinthornw** [comment]
This is available now! https://blog.langchain.dev/week-of-8-7/
