### ISSUE TITLE
Issue: Error Invalid isoformat string after applying start_time filter on UI

### ISSUE THREAD

**Issue by umair313** [langchain-ai/langsmith-sdk#732]
### Issue you'd like to raise.

I applied start_time filter from UI and got this error and I cant reset or remove start_time from filter

![Screenshot 2024-05-24 at 1 20 44 PM](https://github.com/langchain-ai/langsmith-sdk/assets/12728453/6ed2a934-a220-44d1-b92a-f94e20eaa68d)

**Comment by dqbd** [comment]
Should be fixed in LangSmith!
