### ISSUE TITLE
Issue: Traces Not Correctly Attached in runOnDataset

### ISSUE THREAD

**Issue by loui7** [langchain-ai/langsmith-sdk#733]
### Issue you'd like to raise.

We have identified an issue with the tracing functionality when using runOnDataset in conjunction with traceable. The children traces are inconsistently attached to the parent trace, suggesting a race condition.

When running 

```javascript
await runOnDataset(
  predictResult, // Your AI system
  datasetName, // The data to predict and grade over
  {...}
```

where
```
const predictResult = traceable(predictResultFunc, { name: 'predictResult' });
```

and inside `predictResultFunc` is
```javascript
  const callbacks = await getLangchainCallbacks()

  const response = await promptTemplate
    .pipe(getOpenAIClient('gpt-4o'))
    .pipe(parser)
    .invoke(
      {
        ...
      },
      {
        callbacks
      }
    );
```

Sometimes, this is the full result of the trace
![Screenshot 2024-05-26 at 1 08 08 PM](https://github.com/langchain-ai/langsmith-sdk/assets/35469434/93a65cb6-c7b2-468d-a1e5-e66bff92d137)

Sometimes it's this
![Screenshot 2024-05-26 at 1 26 34 PM](https://github.com/langchain-ai/langsmith-sdk/assets/35469434/691c371f-aa22-452a-af27-c27a37045885)

and rarely it includes all of them
![Screenshot 2024-05-26 at 1 28 22 PM](https://github.com/langchain-ai/langsmith-sdk/assets/35469434/609a32a3-bd28-425d-a255-d4ee26d731bd)

Sometimes it also included none at all, but most often it seemed to include at least the `ChatPromptTemplate`

**Comment by hinthornw** [comment]
New evaluator is used now; gonna close
