### ISSUE TITLE
Issue: How to view and delete/rename archived prompts in LangSmith?

### ISSUE THREAD

**Issue by k3vob** [langchain-ai/langsmith-sdk#737]
### Issue you'd like to raise.

I'm not sure if this is the correct place to raise this issue, but I could not think of or find a more suitable place.

I have been experimenting with creating different private prompts in LangSmith. I have archived some prompts after I decided to then experiment with a different template (e.g. switch from Chat Prompt to a Structured Prompt). It appears that you cannot change the template of a prompt, nor delete a prompt, so the only option left is to archive it and then create a new one under the other template. The issue then is that this new prompt cannot use the same name since the old one with the same name still exists, although archived.

Furthermore, I cannot find where to view my archived prompts, so it is getting quite messy not being able to know what prompt names I have already used, so I keep getting a "Prompt not created because a prompt with handle xxx already exists in owner." error when using an intuitive name for a prompt I have already experimented with.

### Suggestion:

Maybe I am missing something, but I would hope for at least one of the following functionalities to be possible:
- View archived prompts
- Delete a prompt
- Delete an archived prompt
- Change the name of a prompt
- Change the name of an archived prompt
- Change the template of a prompt
- Unarchive a prompt

**Comment by hinthornw** [comment]
Thanks for flagging - assigning to @madams0013 to respond; I know viewing/filtering is in flight. I don't think full deletions have been  scheduled yet. I'm unaware of the current status for renaming and unarchiving

**Comment by madams0013** [comment]
Thanks for flagging this! As mentioned, we have filtering for archived prompts at next release.

- View archived prompts -- live at next release
- Delete a prompt -- sometime in the near future
- Delete an archived prompt -- sometime in near future
- Change the name of a prompt -- will discuss with the team
- Change the name of an archived prompt -- will discuss
- Change the template of a prompt -- also a topic of discussion, we're rethinking the process of prompt creation so this will be a part of that conversation.
- Unarchive a prompt -- live at next release (if you go to edit the archived prompt)

Thanks for the feedback! We'll take this all into our discussions.

**Comment by k3vob** [comment]
Thanks to you both. I'll look forward to these new releases!

**Comment by arthberman** [comment]
@madams0013 any update on renaming / archiving ? can be very useful
thanks

**Comment by hinthornw** [comment]
Archiving support is in (has been for a while): 

![image](https://github.com/user-attachments/assets/f1e1164b-7438-4846-8fec-52ac58ed610c)
