### ISSUE TITLE
Issue: NextJS direct tracing

### ISSUE THREAD

**Issue by anton-sementsov** [langchain-ai/langsmith-sdk#743]
### Issue you'd like to raise.

I am using NextJS with the useCompletion and completion API file from Vercel `ai/react` to manage AI requests. 
I tried to trace requests at smith.langchain in different ways but always recive this error `Error in handler LangChainTracer, handleLLMEnd: Error: Invalid UUID: d2d2a5d8-4629-411a-9846cf2c71195666`
Also when last time tried to trace dinamicaly I recived this one `[Error: Failed to batch create run: 401 Unauthorized {"detail":"Invalid token"}]`

I’d really appreciate it if you could help me solve this

**Using next packages:**
 "next": "13.2.4",
 "langchain": "^0.2.2",
 "ai": "^3.1.14",
 "@langchain/core": "^0.2.2",
 "@langchain/openai": "^0.0.34",

**env file:**. (all env I logged, received them properly)
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY=lsv2_......042f4
OPENAI_API_KEY=sk-V...1OtPnY1

**completion.ts file in Next API folder**
```
const model = new ChatOpenAI({
      apiKey: process.env.OPENAI_API_KEY,
      model: 'gpt-3.5-turbo-0125',
      temperature: 0,
    });
```

 ```
   const tracer = new LangChainTracer({ projectName: 'My Project' });

    const stream = await model.stream('Test lang chain', {
      callbacks: [tracer],
    });

    return new StreamingTextResponse(LangChainAdapter.toAIStream(stream));
```

**Comment by jacoblee93** [comment]
Hey @anton-sementsov, we've just shipped 0.2.1 with a new OTEL based approach:

```ts
/**
 * OpenTelemetry trace exporter for Vercel AI SDK.
 *
 * @example
 * ```ts
 * import { AISDKExporter } from "langsmith/vercel";
 * import { Client } from "langsmith";
 *
 * import { generateText } from "ai";
 * import { openai } from "@ai-sdk/openai";
 *
 * import { NodeSDK } from "@opentelemetry/sdk-node";
 * import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node";
 *
 * const client = new Client();
 *
 * const sdk = new NodeSDK({
 *   traceExporter: new AISDKExporter({ client }),
 *   instrumentations: [getNodeAutoInstrumentations()],
 * });
 *
 * sdk.start();
 *
 * const res = await generateText({
 *   model: openai("gpt-4o-mini"),
 *   messages: [
 *     {
 *       role: "user",
 *       content: "What color is the sky?",
 *     },
 *   ],
 *   experimental_telemetry: AISDKExporter.getSettings({
 *     runName: "langsmith_traced_call",
 *     metadata: { userId: "123", language: "english" },
 *   }),
 * });
 *
 * await sdk.shutdown();
 * ```
 */
```

Let us know if that works for you! Docs will follow soon.
