### ISSUE TITLE
Issue: Data not showing up in UI

### ISSUE THREAD

**Issue by janitaportrait** [langchain-ai/langsmith-sdk#755]
I created traces for a project, logging both the nested llm call and the inputs / outputs of the function. I saw the data appear in the dashboard, but when I checked the next day, all of the traces appeared empty and there was no longer any data. Here's an example run ID from the project in question: `8b45061a-1221-42d0-88a3-6ef170fd564b`

This is pretty concerning as I'm not sure I can rely on my data being accessible / viewable. Please let me know how this can be addressed. Appreciate the help, thank you!

### Suggestion:

using my run ID, please clarify if there is a rendering issue preventing the data from showing up, or if it is a data loss issue

**Comment by hinthornw** [comment]
Hi @janitaportrait could you confirm a couple things for us:

1. So you logged a run on day 1 and then revisited it on day 2 (so 24 hours difference), and the run is no longer there. Are any other runs there that would have made it scroll out of view?
2.  Is the time filter set in this project?
![image](https://github.com/langchain-ai/langsmith-sdk/assets/13333726/3a080584-4a65-4d21-9d51-388cd1020a5d)

Are you using the LangSmith cloud or are you on a self-hosted instance? There haven't been any data loss events in our public cloud instance.

**Comment by janitaportrait** [comment]
When I said "all of the traces appeared empty", I meant that I can still see the names of the traces, but there is no data attached to them. I am suspecting it is a UI issue because when I retrieved the same traces with the SDK, I could see their data. Please see attached screenshot. The input and output fields are empty, whereas on the previous day the input and output fields were displaying my logged data as well as the nested LLM calls. 
![image](https://github.com/langchain-ai/langsmith-sdk/assets/152660161/193776ea-2d79-42ca-89ca-e5352b635707)

**Comment by janitaportrait** [comment]
This is from another run using the same tracing code, ie this is what I would expect the traces to look like: 
![image](https://github.com/langchain-ai/langsmith-sdk/assets/152660161/cdaea31e-f658-4cad-9a38-cc4ab2c31770)

**Comment by hinthornw** [comment]
Thanks for clarifying - if you pick "Raw Input" by clicking the dropdown there, does it still show as empty? Or is there content present in the raw payload that is being mis-typed by our frontend?

![image](https://github.com/langchain-ai/langsmith-sdk/assets/13333726/cbc89f1f-ca6a-499c-8cae-3bfff211fbee)

**Comment by janitaportrait** [comment]
The raw input also appears empty 

<img width="792" alt="image" src="https://github.com/langchain-ai/langsmith-sdk/assets/152660161/7d530b0b-7d19-401e-ac79-505f48118b01">

**Comment by hinthornw** [comment]
@janitaportrait was trying to debug this. I may have pushed a fix for it in the latest SDK release. LMK if you still run into issues
