### ISSUE TITLE
Issue: Unable to mask secrets using distributed tracing

### ISSUE THREAD

**Issue by bhanson-techempower** [langchain-ai/langsmith-sdk#763]
## Context

We're using [Prompt Flow](https://github.com/microsoft/promptflow) in our production application and are evaluating LangSmith for observability. Prompt Flow spawns worker threads to distribute work and we're trying to use LangSmith to get visibility in those threads.

We've been able to get threads (OS threads, not LangSmith Threads) working under a unified LangSmith Trace by using distributed tracing. However, LangSmith by default has a very aggressive serializer; it is converting in-memory Prompt Flow connection objects to JSON that were never intended to be serialized as they contain secrets.

We've been able to get the `hide_inputs` functionality working in order to mask this data, but cannot get it to work with distributed tracing. We suspect the distributed tracing functionality is short-circuiting somewhere before the custom `hide_inputs` function gets assigned.

## Observed Behavior

Enabling `hide_inputs` works as expected when configured in the main and child threads:

![image](https://github.com/langchain-ai/langsmith-sdk/assets/51966555/ede3608d-d7e8-4735-b9c6-b9b4befaaee0)

![image](https://github.com/langchain-ai/langsmith-sdk/assets/51966555/338841da-b4a4-4f8f-9a25-3b1ee2e0bcc5)

Without changing anything else, adding a `parent` to set distributed tracing causes the threads to be grouped together appropriately under one Trace, but the `hide_inputs` functionality stops working:

![image](https://github.com/langchain-ai/langsmith-sdk/assets/51966555/3851b1b1-e77c-4a3c-b5bb-e1de1bd8cfa0)

## Expected Behavior

Configuring both options would group them under the same Trace and also utilize the configured `hide_inputs`.

## Steps to Reproduce

I've uploaded a repo with a minimal example that demonstrates the behavior we're seeing.

https://github.com/bhanson-techempower/langsmith-sdk-bug

## Version Info

- python 3.11.3
- langsmith 0.1.71 (also observed on 0.1.59)

## Other Comments

We're open to ideas on how to orchestrate LangSmith with Prompt Flow. We didn't find any information in the documentation on Prompt Flow integration nor multi-threading, and the distributed tracing section of the docs assumes a web framework. LangSmith looks like a great option, but integrating with Prompt Flow has not been simple and we've had to dig in the source a bit to make progress.

If this is a misconfiguration, then raising an exception when both options are present would be helpful.

Alternatively, if LangSmith shipped with default secrets masking capability that would be fantastic.

Thank you!

**Comment by hinthornw** [comment]
Thank you for the detailed repro code! Will address this asap

**Comment by bhanson-techempower** [comment]
Thank you for the lightning fast turnaround! Confirmed fixed. 🎉

**Comment by hinthornw** [comment]
awesome - thanks for the confirmation! Let us know how everything goes w/ the promptflow + langsmith integration!
