### ISSUE TITLE
Issue: Wrong Token Count for LangChain's Tool Calling Agent

### ISSUE THREAD

**Issue by simon-enosis** [langchain-ai/langsmith-sdk#786]
### Issue you'd like to raise.

I am using LangSmith to monitor an AI application I've developed with LangChain, specifically leveraging the `Tool Calling Agent`. However, I've noticed a significant issue with the token count displayed in LangSmith. The platform only counts text from the system, human, AI, and similar sections as input tokens, **ignoring the tool details**. According to OpenAI's documentation, all function details should be counted as input tokens (A doc snippet has been attached). This discrepancy results in an **inaccurate token count and cost being reported**.

The snippet from OpenAI's doc
![image](https://github.com/langchain-ai/langsmith-sdk/assets/89076010/61c7fb8b-ea40-4ed0-8642-71d0fd4cb1ab)

**Comment by hinthornw** [comment]
@simon-enosis do you have any more information about how to reproduce the issue?

Running this code:
```python
from langchain_openai import ChatOpenAI

long_docstring = "".join(f"{i} 🙈" for i in range(200))


def my_tool(query: str):
    return "the answer"


my_tool.__doc__ = long_docstring


model = ChatOpenAI(model="gpt-3.5-turbo")
bound_model = model.bind_tools([my_tool])
result = model.invoke("hello", {"tags": ["no_tools"]})
result = bound_model.invoke("hello", {"tags": ["with_tools"]})

```

Gives these traces:

1. With tools (851 tokens reported in langsmith): https://smith.langchain.com/public/7642075b-6edf-47af-8cfb-83da34253575/r
2. Without tools (17 tokens reported in langsmith): https://smith.langchain.com/public/fa2c2043-00fb-411d-bf4c-be8a77fdab47/r


Which account for tool token counts.

**Comment by simon-enosis** [comment]
@hinthornw, 

To reproduce the issue, please follow these steps:
1. Create a Tool Calling Agent using LangChain.
2. Create a few custom tools.
3. Bind the tools.
4. Run the agent using the agent executor from LangChain.


To provide you with an example scenario, I have created the following traces:
1. [With 1 tool](https://smith.langchain.com/public/f193084c-895f-427e-a016-f4107db781e7/r): 60 tokens
2. [With 4 tools](https://smith.langchain.com/public/99d14012-bf3f-4ab0-a938-38dc21139c1a/r): 60 tokens

**Comment by hinthornw** [comment]
Oh that indeed looks incorrect! Thanks for sharing the traces, this is helpful
