### ISSUE TITLE
Issue: nested traces logged as individual traces

### ISSUE THREAD

**Issue by guidorietbroek** [langchain-ai/langsmith-sdk#806]
### Issue you'd like to raise.

When creating a `LangGraph` some nested traces are logged as individual traces. See screenshot.

Below you can find the code. I simplified it a little bit so the basic function is better visible.

```typescript
const app = workflow.compile();

const runResponseGenerator = traceable(
  async function runResponseGenerator(
    query: string
  ) {
    return app.invoke({
    keys: {
      question: query
    },
  });
  },
  { name: "Answer generator", run_type: "chain"}
);

export default runResponseGenerator;
```

When looking at the traces in Langsmith, I see that LangGraph and the retriever are nested inside the main trace, but also logged as individual traces. These traces are very minimal, not showing the used tokens for instance. It happens with every retriever btw, so if I need to make 3 retrievals, then I get 3 extra traces. 

The LangGraph invoke is not wrapped inside a traceable, but I tested this as well with the same result. The retriever is wrapped in a main traceable (run_type = chain) and inside this traceable another traceable for the invoke of the retriever (run_type = retriever).

So, the main trace is fully working as expected and needed, it is just that I receive extra traces not needed because they are already nested.

<img width="357" alt="Scherm­afbeelding 2024-06-20 om 07 19 39" src="https://github.com/langchain-ai/langsmith-sdk/assets/86220425/6a090d42-c551-4d9c-bfc5-9d9a1eb5458d">

### Suggestion:

These extra traces should not happen.

**Comment by mrdrprofuroboros** [comment]
I'm facing the same issue and as far as I understood the root cause is somewhere in the difference between the sync and the async implementations. Here's a minimal example:

Sync works fine and glues the trace in one
```python
from typing import Annotated

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
from typing_extensions import TypedDict

from langgraph.graph import StateGraph
from langgraph.graph.message import add_messages

class State(TypedDict):
    messages: Annotated[list, add_messages]

llm = ChatOpenAI(model = "gpt-4o", temperature = 0.2)

def chatbot(state: State):
    return {"messages": [llm.invoke(state["messages"])]}

graph_builder = StateGraph(State)
graph_builder.add_node("chatbot", chatbot)
graph_builder.set_entry_point("chatbot")
graph_builder.set_finish_point("chatbot")
graph = graph_builder.compile()

inputs = {"messages": [HumanMessage(content = "LangSmith is fine with sync functions")]}
for s in graph.stream(inputs):
    print(s)
```

Yields one trace with OpenAI call in it

<img width="597" alt="Снимок экрана 2024-08-01 в 18 11 41" src="https://github.com/user-attachments/assets/446d76b1-8e6c-4072-865a-545c36f72bf5">


Now changing to async:
```python
async def chatbot(state: State):
    return {"messages": [await llm.ainvoke(state["messages"])]}

graph_builder = StateGraph(State)
graph_builder.add_node("chatbot", chatbot)
graph_builder.set_entry_point("chatbot")
graph_builder.set_finish_point("chatbot")
graph = graph_builder.compile()

inputs = {"messages": [HumanMessage(content = "Why don't you like async?")]}
async for s in graph.astream(inputs):
    print(s)
```

Splits the traces
<img width="594" alt="Снимок экрана 2024-08-01 в 18 14 19" src="https://github.com/user-attachments/assets/84a51908-677b-4537-8a92-62e9c313e877">

**Comment by hinthornw** [comment]
This happens in python < 3.11 if you are doing async invocation and aren't manually passing the RunnableConfig through.


ContextVars don't work properly in python until 3.11 so :

1. If you can update python versions, do so.
2. If not, pass through the runnable config:
```
async def chatbot(state: State, config: RunnableConfig):
    return {"messages": [await llm.ainvoke(state["messages"], config)]}
```
