### ISSUE TITLE
DOC: Quick start for Log in browser

### ISSUE THREAD

**Issue by themez** [langchain-ai/langsmith-sdk#818]
### Issue with current documentation:

The current method for wrapping utilizes an async hook, which is available in the Node.js runtime but not in the browser.
```
import { wrapOpenAI } from "langsmith/wrappers";
```

Is there an alternative way to trace OpenAI SDK calls in a browser environment?

**Comment by hinthornw** [comment]
cc @dqbd I'm not aware of a recommended way for this, given that tracing currently would require putting a key within the browser code as well

**Comment by hinthornw** [comment]
We aren't prioritizing in-browser tracing at this moment
