### ISSUE TITLE
LangSmithConnectionError

### ISSUE THREAD

**Issue by baiziyuandyufei** [langchain-ai/langsmith-sdk#819]
### Issue you'd like to raise.

2024-06-24 20:05:22,709 WARNING Failed to batch ingest runs: LangSmithConnectionError("Connection error caused failure to POST https://api.smith.langchain.com/runs/batch  in LangSmith API. Please confirm your internet connection.. ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))")

**Comment by hinthornw** [comment]
Could you confirm your langsmith version, share more info on what workload you are running, share more information about your connectivity level, etc.?

**Comment by baiziyuandyufei** [comment]
it’s my vpn, lead in this error.发自我的 iPhone在 2024年6月26日，00:13，William FH ***@***.***> 写道：﻿
Could you confirm your langsmith version, share more info on what workload you are running, share more information about your connectivity level, etc.?

**Comment by douglasqian** [comment]
+1 seeing this as well on 100+ Mbps download & upload without VPN

Running latest version as of writing (v0.1.111) of the SDK and using `aevaluate`

**Comment by hinthornw** [comment]
For future readers, this can also often happen when the content-length is too large. We now log the content lenght and try to update the recommendation when we see large payloads that fail and will work in improving the errors that are raised from the load balancer as well.

Can filter things out  to reduce size: https://docs.smith.langchain.com/how_to_guides/tracing/mask_inputs_outputs
