### ISSUE TITLE
Allow access to `list_repos` for private repos from langchainhub

### ISSUE THREAD

**Issue by codekiln** [langchain-ai/langsmith-sdk#825]
### Feature request

[Push/pull a prompt | 🦜️🛠️ LangSmith](https://docs.smith.langchain.com/how_to_guides/prompts/pull_push_a_prompt) documents how to use python to push or pull individual prompts by name, and that works for me. 

I'd also like to be able to execute `langchainhub.client.Client.list_repos` that are private to my organization (I'm a Premium Plus member with 8 seats). Correspondingly, I'd like to be able to do `hub.list_prompts(search_kwargs))` to search and list my organization's prompts with my `LANGCHAIN_API_KEY`.

Today, calling `Client.list_repos()` returns `requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`, even when an equivalently configured client does allow pushing and pulling prompts with `push_repo` and `pull_repo`.

### Motivation

We'd like our business stakeholders to be able to author private prompts in LangSmith, then we'd list those available prompts in our prototyping UI to enable interacting with them. This would hopefully allow us to have better versioning and LangSmith integration out of the box.

**Comment by codekiln** [comment]
Is there a better repository for this? I could not find the langchain github repo for the `langchainhub` python package.

**Comment by hinthornw** [comment]
We are moving it here soon

**Comment by hinthornw** [comment]
You can now use `client.list_prompts(..)`

**Comment by lngcordell** [comment]
yes please, I'd also like to be able to create a deployment using private repo

<img width="812" height="201" alt="Image" src="https://github.com/user-attachments/assets/f88ca925-cf00-46bc-b557-28e1209585db" />
