### ISSUE TITLE
Issue: Some traced runs don't log tokens

### ISSUE THREAD

**Issue by omrish-Glossai** [langchain-ai/langsmith-sdk#832]
Hello.
I've deployed tracing code to my dev env and noticed some of the traced runs seem to be logged without any token information. 
When checking the traces, It shows the prompt is full of text as usual and the output is as expected.
Any ideas on why such a thing happens?

Adding a photo to show some runs were traced properly while others failed:
![Screenshot 2024-07-01 113520](https://github.com/langchain-ai/langsmith-sdk/assets/103045926/e0259291-16d4-4ed0-8a74-8b2df370371a)

**Comment by hinthornw** [comment]
Could you share code or a run where this occurs?

**Comment by omrish-Glossai** [comment]
Upon further inspection, it seems like this happens when the prompt has more than 3 pictures in it. Every time I try running something with more than 3 photos the tokens are zero.

**Comment by hinthornw** [comment]
Python or JS? Is this logged with LangChain code? Or a custom decorator? Or something else?

What model provider? OpenAI?

**Comment by omrish-Glossai** [comment]
I am using Python and logging with Langchain code. This occurred both with anthropic's claude and openai's gpt-4o

**Comment by hinthornw** [comment]
What versions of the LangChain OpenAI and LangChain Anthropic packages are you using? Could you share a minimum code example please?

**Comment by omrish-Glossai** [comment]
langchain-openai==0.0.8
langchain-anthropic==0.1.15
I can't share my exact code, unfortunately. It is something along the lines of:
`
    init_key(env=env) # initiate the langsmith API key
    os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
    os.environ["LANGCHAIN_TRACING_V2"] = "true"
    env = env or get_env()
    os.environ["LANGCHAIN_PROJECT"] = env # Setting the project as the current environment 
...
...
...
chain.invoke(
            {},
            {
                "run_name": "analyze_post",
                "metadata": {
                    ...
                },
            },
        )
`
