### ISSUE TITLE
Issue: LangSmith is not correctly logging the metadata field when calling the chain via the .stream() method. 

### ISSUE THREAD

**Issue by thiagotps** [langchain-ai/langsmith-sdk#839]
### Issue you'd like to raise.

The following code
```python
from langchain_core.prompts import ChatPromptTemplate
from langchain_aws import ChatBedrockConverse
from langchain_core.runnables import RunnableAssign,RunnablePassthrough
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.output_parsers import StrOutputParser
import uuid

model = ChatBedrockConverse(model="anthropic.claude-3-haiku-20240307-v1:0", client=client)

prompt = ChatPromptTemplate.from_messages([
("system", "You are a helpful bot that will put an emoji on every answer."),
("placeholder", "{messages}")])

chain = {"messages": RunnablePassthrough()} | prompt | model | StrOutputParser()
chain.invoke([HumanMessage(content="What is LangChain ?")], {"metadata": {"session_id": str(uuid.uuid4()), "user": "random_user"}, "run_name": "Bot"})
```
correctly logs the metadata in the LangSmith platform, as shown by this print

![image](https://github.com/langchain-ai/langsmith-sdk/assets/8174647/cb5e0117-fd9f-4297-b0b7-1e466945e2ad)

But the when calling the chain via the .stream() method, that is:
```python
for answer in chain.stream([HumanMessage(content="What is LangChain ?")], {"metadata": {"session_id": str(uuid.uuid4()), "user": "random_user"}, "run_name": "Bot"}):
    print(answer, end='')
```

The following log appears in LangSmith:
![image](https://github.com/langchain-ai/langsmith-sdk/assets/8174647/45daede8-fb6d-4f04-ae86-6013a6f02751)
Note that the metadata defined above in the code is not showing up.

Interestingly, the metadata fields are not stored in the top run but are still being stored in the call to the model.
![image](https://github.com/langchain-ai/langsmith-sdk/assets/8174647/2e04f614-a7d4-4854-b5f1-0f9924330f59)
![image](https://github.com/langchain-ai/langsmith-sdk/assets/8174647/14fcab6d-630d-49ab-b101-699fa183f11b)

Here are the package versions in use: 
```txt
langchain                       0.2.6           
langchain-aws                   0.1.9           
langchain-cohere                0.1.8           
langchain-community             0.2.6           
langchain-core                  0.2.10          
langchain-postgres              0.0.9           
langchain-text-splitters        0.2.2           
langchainhub                    0.1.20          
langsmith                       0.1.82          
```

**Comment by hinthornw** [comment]
Oh interesting - thanks for flagging, and thank you for the helpful reproducible example - makes it way easier to address
