### ISSUE TITLE
Issue: type hint for the `evaluators` arg of `evaluate` is too restrictive

### ISSUE THREAD

**Issue by mobiware** [langchain-ai/langsmith-sdk#847]
### Issue you'd like to raise.

The `evaluators` argument to the `evaluate` function (from `langsmith.evaluation` package) is typed as a sequence of `EVALUATOR_T`, which is defined as:
```
EVALUATOR_T = Union[
    RunEvaluator,
    Callable[[schemas.Run, Optional[schemas.Example]], EvaluationResult],
]
```

However, custom evaluators can also return an `EvaluationResults` that wraps multiple `EvaluationResult`s together, as can be seen in the Langsmith SDK source code.

This is confirmed by our own experience, as well as Langsmith official documentation:
https://docs.smith.langchain.com/how_to_guides/evaluation/evaluate_llm_application#return-multiple-scores

Because of this, `mypy` returns an error on the code below (on the `evaluators=[evaluate_precision_recall],` line) even though the code runs fine and the expected evaluation feedback is properly attached to the experiment's runs:

`error: List item 0 has incompatible type "Callable[[Run, Example | None], EvaluationResults]"; expected "RunEvaluator | Callable[[Run, Example | None], EvaluationResult]"`

```
from typing import Optional

from langsmith import EvaluationResult
from langsmith.evaluation import evaluate, EvaluationResults
from langsmith.schemas import Example, Run

def evaluate_precision_recall(run: Run, example: Optional[Example]) -> EvaluationResults:
    reference = set(example.outputs["data"] if example and example.outputs else [])
    detected = set(run.outputs["data"] if run.outputs else [])

    true_positives = detected.intersection(reference)
    true_positives_count = len(true_positives)

    return EvaluationResults(
        results=[
            EvaluationResult(key="precision", score=true_positives_count / len(detected)),
            EvaluationResult(key="recall", score=true_positives_count / len(reference)),
        ]
    )


experiment_results = evaluate(
    chain.invoke,
    data="<dataset-name>",
    evaluators=[evaluate_precision_recall],
    experiment_prefix="test",
)
```

### Suggestion:

`EVALUATOR_T` should be changed to:

```
EVALUATOR_T = Union[
    RunEvaluator,
    Callable[[schemas.Run, Optional[schemas.Example]], EvaluationResult | EvaluationResults],
]
```

In fact `AEVALUATOR_T` already allows `EvaluationResults` return values:
```
AEVALUATOR_T = Union[
    Callable[
        [schemas.Run, Optional[schemas.Example]],
        Awaitable[Union[EvaluationResult, EvaluationResults]],
    ],
]
```

**Comment by hinthornw** [comment]
Good catch. Will land a change in a bit

**Comment by hinthornw** [comment]
Should be done
