### ISSUE TITLE
Issue: Organizational workspace does not track metrics from LangSmith evaluate

### ISSUE THREAD

**Issue by cg94301** [langchain-ai/langsmith-sdk#856]
### Issue you'd like to raise.

I'm using LangSmith evaluate function (from langsmith.evaluation import evaluate) to produce a simple correctness metric. This works perfectly fine when I use the Personal account which is linked to my corporate email. But when I switch to using the actual assigned workspace inside my organizational account  the metric is not traced anymore. The metrics are still produced alright, but it seems the run hangs trying to log the traces with the workspace. Since simple switching from one workspace to another, inside the same account, breaks tracing, the issue seems to be with the workspace.

**Comment by hinthornw** [comment]
Thanks for flagging. How are you configuring the API key for your org workspace?

My suspicion is that some values aren't inheriting the manual client you're passing in and instead are reading from the environment (If that's the case, it'd be a a bug that I will fix, though it can be worked around by setting the workspace info in the environment)

**Comment by cg94301** [comment]
We fell victim to data retention auto-upgrades. Our plan was to only use basic 14 day retention. Hence the admin set Extended Trace Limit to 0. However, little did we know that this is not fully under our control. Using the evaluate function does generate feedback and hence triggers an auto-upgrade. That means extended traces will be generated and the limit cannot be set to zero.

This also explains why we still saw the regular runs, they are considered basic, and no metric runs, those are considered feedback producing and hence extended.

For anyone interested auto-upgrades are documented here: https://docs.smith.langchain.com/concepts/usage_and_billing/data_retention_billing#data-retention-auto-upgrades

Thank you for the follow up! You can consider this issue resolved.
