### ISSUE TITLE
Issue: Custom cost tracking for langsmith calls 

### ISSUE THREAD

**Issue by krrishdholakia** [langchain-ai/langsmith-sdk#858]
### Issue you'd like to raise.

Hi, I'm trying to log custom cost to langsmith. 

Here's my sample curl request: https://gist.github.com/krrishdholakia/434b1ef66decdb2e37b162537a615604

I'm following the format mentioned in docs: https://docs.smith.langchain.com/reference/data_formats/run_data_format

but i don't see the cost logged on UI 
<img width="1293" alt="Screenshot 2024-07-09 at 9 16 10 AM" src="https://github.com/langchain-ai/langsmith-sdk/assets/17561003/a4320748-e430-42e9-9268-6c45326b4c02">

cc: @dqbd @hinthornw @eyurtsev

**Comment by krrishdholakia** [comment]
Observations: 

when i look at the api swagger, `total_cost` isn't mentioned there - https://api.smith.langchain.com/redoc#tag/run/operation/create_run_api_v1_runs_post

this makes me think, this isn't actually supported by the langsmith api

**Comment by hinthornw** [comment]
Today, cost info is computed from the token counts. Token counts can be sent up on a runwise basis and then the costs are estimated based on the patterns you configure for your workspace.

![image](https://github.com/langchain-ai/langsmith-sdk/assets/13333726/69fd031b-6f3d-4d07-abe4-35dea19f6c80)

**Comment by krrishdholakia** [comment]
hey @hinthornw i can see `total_cost` as a mentioned param on the api docs 
<img width="1111" alt="Screenshot 2024-07-10 at 9 15 00 AM" src="https://github.com/langchain-ai/langsmith-sdk/assets/17561003/eaadf87f-e7a7-4a4f-afc7-83307fe9c6ef">

https://docs.smith.langchain.com/reference/data_formats/run_data_format


is this not the case?

**Comment by hinthornw** [comment]
It's a computed value. It's present on the run resource as an aggregation of the tokens within child runs.

It's not a a field in the request body itself: https://api.smith.langchain.com/redoc#tag/run/operation/create_run_api_v1_runs_post

**Comment by krrishdholakia** [comment]
Hi @hinthornw saw this is marked as completed. 

Can you share any docs on how i can do custom cost tracking?

**Comment by hinthornw** [comment]
https://docs.smith.langchain.com/how_to_guides/tracing/calculate_token_based_costs

**Comment by krrishdholakia** [comment]
Hi @hinthornw can we please re-open this issue? 

The suggested doc, doesn't let me just log my cost to langsmith. We have our own model cost map, and use it for logging to langsmith + other logging places + internal budgeting logic on our server. 

<img width="1054" alt="Screenshot 2024-09-20 at 7 45 27 AM" src="https://github.com/user-attachments/assets/1a529e7b-2c6e-493d-837b-786cd27cc83f">

**Comment by hinthornw** [comment]
Yeah that would be preferred

**Comment by maxmamis** [comment]
+1, have a use-case involving API usage costs (no tokens involved), would love to be able to track these costs and sum them with token costs across a run

**Comment by tanushree-sharma** [comment]
@vaibhav-artisan we do't support Perplexity's cost tracking at the moment, however as a workaround you can compute yourself and costs directly to LLM calls https://docs.smith.langchain.com/observability/how_to_guides/calculate_token_based_costs#send-costs-directly

**Comment by tanushree-sharma** [comment]
@maxmamis today we ignore costs for non-llm runs so you'd have to hack it by setting run_type='llm'

```
from langsmith import traceable

@traceable(run_type='llm', metadata={"usage_metadata": {"total_cost": 0.25}})
def exa(x):
    return x

exa('...')
```
