### ISSUE TITLE
DOC: Documentation for the expect utility uses "expectation" instead of "reference" in embedding_distance args

### ISSUE THREAD

**Issue by mobiware** [langchain-ai/langsmith-sdk#868]
### Issue with current documentation:

Documentation for the `expect` utility uses the wrong argument to the `embedding_distance()` method in the code sample
https://docs.smith.langchain.com/how_to_guides/evaluation/unit_testing#expectations

The code sample uses the `expectation` arg but the real argument name is `reference`

**Comment by hinthornw** [comment]
Good catch
