### ISSUE TITLE
Add an `atrace` context manager? Or handle serialization/copying in `trace` in a separate thread?

### ISSUE THREAD

**Issue by ldorigo** [langchain-ai/langsmith-sdk#882]
### Feature request

`trace` runs everything on the main thread which means that filtering, serialization etc. all has to happen synchronously with the main logic and can significantly slow things down. As far as I understand this is not the case with the tracing that happens in langchain. Could you add an `atrace` version of `trace` or implement `trace` such that it doesn't block the main thread?

### Motivation

Tracing shouldn't have massive impacts on the application performance.

**Comment by hinthornw** [comment]
Ya I was thinking of adding this actually. Makes sense to me

**Comment by ldorigo** [comment]
I'm not sure how exactly it's implemented so far but it would perhaps make sense to push all of langsmith's processing in a whole separate process (so run it in parallel, not concurrently). `deepcopy`'s and serializations are CPU-bound and can be really slow for big objects, so doing it asynchronously will still impact the traced application's performance (in the sense that it will consume a lot of CPU cycles which are shared by all async functions).

**Comment by hinthornw** [comment]
Ya we've talked about it. It would add complexity since multiprocessing isn't supported on all machines and we'd still have to be using ipc. 
First step is definitely making sure io-bound tasks aren't run in the main thread

**Comment by ldorigo** [comment]
Sure, I understand. Do you have a rough idea of when the first non-blocking version might be released? (this is currently blocking us, I need to decide whether to implement a workaround myself or just wait for it to be supported :-) )

**Comment by ldorigo** [comment]
I'm not sure this really solved the problem - consider the following setup:


```
def slow_langsmith(inputs: dict) -> dict:
    for i in range(30):
        time.sleep(1)
        print("waiting")
    return inputs


LANGSMITH_CLIENT = LangSmithClient(
    hide_inputs=filter_langsmith, hide_outputs=filter_langsmith, timeout_ms=(250000, 250000)
)

```

If I do 

```
async with trace(inputs={}):
    print("tracing!")
```

This still seems to wait for the entire 30 seconds before actual "tracing" gets printed.

**Comment by ldorigo** [comment]
(@hinthornw ; not sure you get notifs for closed issues)
