### ISSUE TITLE
Issue: Internal Server Error when trying to add metadata to dataset example

### ISSUE THREAD

**Issue by Gregliest** [langchain-ai/langsmith-sdk#889]
### Issue you'd like to raise.

In the UI, in Dataset->Example->Edit->Metadata->Add Metadata. When I try to add a key/value pair I get "Error updating metadata, Internal Server Error". 

This is blocking our ability to use the Langsmith platform for certain types of tests that we'd like to run.

**Comment by hinthornw** [comment]
Sorry to hear about that! Are you using LangSmith Cloud? Or is this self-hosted? Is this happening for all metadata you're adding or is it only for some? And what type of dataset are you using?

I am unable to reproduce your error right now, so any additional information would help.

**Comment by Gregliest** [comment]
This looks like it's working now, thanks for your attention.
