### ISSUE TITLE
BUG: nested `with trace():` are no longer displayed as nested on langsmith with async trace?

### ISSUE THREAD

**Issue by ldorigo** [langchain-ai/langsmith-sdk#892]
### Issue you'd like to raise.

```
def some_function():
   print("hey hey")
   with trace(inputs={}):
       print("my my")

with trace(inputs={}):
   some_function()
```
This used to result in nested runs on langsmith. 
Since you implemented `async with trace()`; the async version of this code no longer properly nests the runs on langsmith?

**Comment by hinthornw** [comment]
That's embarrassing. Thanks for flagging.
