### ISSUE TITLE
Get Langsmith Execution URL after invoke

### ISSUE THREAD

**Issue by GaelCangySpoon** [langchain-ai/langsmith-sdk#897]
### Feature request

Get Langsmith Execution URL after invoke

### Motivation

Easier for debugging purposes

**Comment by GaelCangySpoon** [comment]
@dosu is it possible to get the langsmith url after invoke of a sequence?

**Comment by hinthornw** [comment]
There's `get_run_url` if that's what you're asking? Though it pings the server, so it's intended usage is for analysis after the fact rather than in the hot path

**Comment by hinthornw** [comment]
LMK if you need more info!
