### ISSUE TITLE
Pull configurations for prompt

### ISSUE THREAD

**Issue by antonsamilyk** [langchain-ai/langsmith-sdk#910]
### Feature request

Add functionality to pull configurations for particular prompt. Pulling model type, temperature, JSON mode switch, etc. 

### Motivation

It will help to create more flexible AI pipelines. For now developers have to pull prompts and manually change configs for particular model and run.

**Comment by hinthornw** [comment]
Hi @antonsamilyk , have you tried using `include_model=True` ?
