### ISSUE TITLE
DOC: Enable Tracing in Langsmith

### ISSUE THREAD

**Issue by HarishContinube** [langchain-ai/langsmith-sdk#914]
### Issue with current documentation:

We don't want to store the LangSmith tracing credentials in the environment.
Is there any other way to enable tracing without setting the credentials in the environment? 
Is there an option to dynamically configure the LangSmith tracing configurations?

**Comment by hinthornw** [comment]
Would the doc "Trace without setting environment variables" address your question? https://docs.smith.langchain.com/how_to_guides/tracing/trace_without_env_vars

**Comment by hinthornw** [comment]
LMK if you need more info!
