### ISSUE TITLE
Issue: New Playground view

### ISSUE THREAD

**Issue by Darwinium** [langchain-ai/langsmith-sdk#923]
### Issue you'd like to raise.

Today, the whole team was surprised to see that you updated the Playground page (see below). I don't know why you decided to do so, but the decision was made by someone who never worked with Langsmith. For us, it's a tool for everyday work; we have many prompts, and we must adjust them almost every day, and the way how the Playground looked was perfect. 

But now you need to change the prompt, scroll down to see the output, scroll up, click on setting and change setting in pop up, click save, scroll down to see the result. This is a nightmare and we even started to look for browser extensions where you can change the HTML on the website to make it more convenient.

<img width="1441" alt="Screenshot 2024-08-15 at 10 11 17" src="https://github.com/user-attachments/assets/5eb91b59-f558-427a-a2af-df026a29e6a5">

### Suggestion:

Please let us return to the previous version of this page, and before changing this crucial functionality, please ensure that you know the reasons for changing.

Thank you.

**Comment by hinthornw** [comment]
Hi @Darwinium - thanks for voicing feedback about the adjusted playground experience! And thanks for your patience.

We are pushing out some changes to reduce the scrolling incurred by the linear view try to regain the niceties of the previous layout. I think we're generally in agreement about the worse tradeoffs with this version (worse horizontal usage of space when using a single LLM; too much scrolling for mid-to-longer prompts).

For context, this change was made in part to unify the various playground experiences and make it easier to transition to comparing models/prompts in a shared input.

In the future I'd appreciate if you refrain from ad hominem on the developer working to balance requests from various parties here.

Will keep you posted when we get a fix out.

**Comment by hinthornw** [comment]
@Darwinium actually I believe some of htose changes are already out this morning. Do you have feedback on the adjusted playground?

![image](https://github.com/user-attachments/assets/e34f167d-631f-4c78-b36a-611452d59a06)

**Comment by Darwinium** [comment]
I forgot to say that it looks like you use the big screen as a second display. In my case, I work from a 15-inch MacBook.

**Comment by hinthornw** [comment]
OH that's a good callout re: scrolling for the button - will see if we can get an adjustment made

**Comment by hinthornw** [comment]
@Darwinium I believe some changes have been landed to ensure the button remains visible for long prompts - do you have any remaining difficulties with the new layout?

**Comment by Darwinium** [comment]
@hinthornw hi 👋
Thank you for letting me know! Much better, thanks. There's just a small issue but nothing crucial. Please see the screenshot below:
<img width="1708" alt="Screenshot 2024-08-22 at 09 35 21" src="https://github.com/user-attachments/assets/e1aee2dd-e196-4956-87ba-531592b27156">

**Comment by hinthornw** [comment]
We're going to do a larger redesign of the app experience and will keep imrpoving. Thank you again for reporting!
