### ISSUE TITLE
Issue with create_feedback() in Client of Langsmith

### ISSUE THREAD

**Issue by CronusCipher** [langchain-ai/langsmith-sdk#947]
### Issue you'd like to raise.

I have a simple LLM chatbot application wich created by LangChain. Now I want to use LangSmith for monitoring and tracing the application. everything is straightforward. I can trace all of inputs and results in LangSmith dashboards. but when I want to add feedback features to these traces, I am facing an error that seems to be because of `Client` class and `create_feedback()` on it. 
I get the `run_id` and I can print it, but when I want to assign this parameter to `create_feedback()` function, facing this error:

`TypeError: Client.create_feedback() missing 1 required positional argument: 'run_id'`

I tried everything from changing the `rud_id` data type to even uninstall and install the LangSmith package again.

In the below tou can see the split of my code breifly where the error arised.
If you experienced same issue or have any idea regarding this issue, please share your knowledge

```
run_id=run_collector.traced_runs[0].id 

client=Client

feedback=client.create_feedback(
                run_id,
                key=key,
                score=score,
                comment=comment
            )
```

**Comment by hinthornw** [comment]
Looks like you never created a client here. Should be:

```
client = Client()
```
Instead of
```
client = Client
```
