### ISSUE TITLE
Load Prompt not from hub when creating an evaluator

### ISSUE THREAD

**Issue by Lukecn1** [langchain-ai/langsmith-sdk#965]
### Feature request

As the title suggest, I want to be able to use a prompt I have saved and committed, but havent published on the public hub. 

### Motivation

The reason is that we need to keep our prompts private.

**Comment by hinthornw** [comment]
So a private prompt? It should be possible already: what errors are you seeing?

**Comment by Lukecn1** [comment]
I dont see an error, in the UI when creating an evaluator for a dataset, I cant select a private prompt as the template for the evaluator - only public prompts from the hub.

**Comment by hinthornw** [comment]
Oh that's indeed frustrating. I'll forward to the team

**Comment by Lukecn1** [comment]
Yes exactly, when I go to select a prompt from the hub, I am not able to select any other than public ones, hence those I have , which are private, are not listed.

**Comment by hinthornw** [comment]
Hi @Lukecn1 FYi the prompt has to be a **structure prompt** FYI but I believe this should be supported today. Could you confirm that the prompt you're looking to access is a structured prompt?

**Comment by Lukecn1** [comment]
That works yes, thanks for clearing that up. I was not aware that I needed to specify and output schema for it to be used as a evaluator. 

Thanks for the responses :)
