### ISSUE TITLE
How does Langsmith evaluate tool_input for api actions

### ISSUE THREAD

**Issue by depshad** [langchain-ai/langsmith-sdk#967]
### Issue you'd like to raise.

I would like to understand how can I get the tool_input which is shown in langsmith traces for api actions with openai assistants. This will be helpful while debugging api actions.

**Comment by hinthornw** [comment]
Could you provide more context on what your code looks like?

**Comment by hinthornw** [comment]
Feel free to re-open with more details, but as it stands there isn't an actual issue.
