### ISSUE TITLE
Remove or increase the 15 example limit in the playground

### ISSUE THREAD

**Issue by Lukecn1** [langchain-ai/langsmith-sdk#968]
### Feature request

As  the title suggests. 

I want to run experiments on the entire test dataset I have uploaded, using the prompts I have written and comitted in the langsmith client. 

At least allow me to remove it when self-hosting langsmith. 

### Motivation

I like using langsmith to track prompts and their performance on datasets, but having to manually write things in a python script every time, when I just as well could run it in the playground, is not a preferable solution to me. 

Langsmith makes it really easy to track both prompts and experiments, but with the 15 example limit, the playground environment is entirely unusable for larger more comprehensive experimentation.

**Comment by hinthornw** [comment]
Thanks for the request! This is on the near-term roadmap; agreed the constraint is cumbersome

**Comment by Lukecn1** [comment]
Sounds good, thanks for the response :) 

In the meantime before its rolled out, is there a way to remove this restriction when self-hosting?

**Comment by hinthornw** [comment]
Not at present; the restriction is placed because we do most of this in the browser today. Hoping to remove it sometime this month (would involve running it server side)

**Comment by Lukecn1** [comment]
Alright, thanks for the response :) Looking forward to the restriction being lifted ;)

**Comment by madams0013** [comment]
The playground now supports running over an entire dataset! When you run over a dataset, it will run over the entirety of the dataset.

The UI shows the first 20 examples and then there's a link to the full experiment from there.

Feel free to reach out if you have any other questions! Cheers
