### ISSUE TITLE
Failed to batch ingest runs

### ISSUE THREAD

**Issue by guapia233** [langchain-ai/langsmith-sdk#970]
### Feature request

I am learning an official langgraph sample code, link:. https://github.com/langchain-ai/langgraph/blob/main/examples/multi_agent/hierarchical_agent_teams.ipynb

 It worked fine locally, but I kept getting errors when I tried to trace the project with the following two lines:
environ["LANGCHAIN_TRACING_V2"] = "true" environ[" langchain_tracing_v2 "] = "true"
environ["LANGCHAIN_PROJECT"] = "hierarchical_agent_teams". And it keeps getting errors:
![1725437994898](https://github.com/user-attachments/assets/02611073-e347-4118-aef5-23d2947077a8)

### Motivation

Asking for help here, thanks!

**Comment by guapia233** [comment]
I've already written LANGCHAIN_API_KEY in the system environment variable.

**Comment by hinthornw** [comment]
This can happen in two cases:

1. The environment isn't actually being set correctly / the API key that's being set isn't valid.
2. The payload size is too large.

Could you print out the api key beroe the call to stream to help us rule outt he former?
