### ISSUE TITLE
Support LLM token count and metadata for Vercel AI SDK

### ISSUE THREAD

**Issue by zirkelc** [langchain-ai/langsmith-sdk#999]
### Feature request

LangSmith does not show the token count for traces created from `wrapAISDKModel` for the Vercel AI SDK. The counts are sent to LangSmith:

```yaml
usage:
  promptTokens: 872
  completionTokens: 28
``` 

However, the counts are not rendered in the UI. Also, any [metadata](https://sdk.vercel.ai/docs/ai-sdk-core/telemetry#telemetry-metadata) added via `experimental_telemetry.metadata` is not sent to LangSmith.

### Motivation

I'm exploring the usage of Vercel AI SDK while keeping the good DX from LangSmith.

**Comment by agola11** [comment]
Thanks for flagging @zirkelc. We are hoping to fix at least the token counting issue very soon

**Comment by Boohi** [comment]
Any updates on this? This is a quite critical feature to have on customer-facing applications

**Comment by jacoblee93** [comment]
Hey @Boohi, we've just shipped 0.2.1 with a new OTEL-based approach:

https://github.com/langchain-ai/langsmith-sdk/pull/1104

Docs will follow soon!
